/**
 * Measured preview heights in px, keyed by the example's path under `/blume-examples/`.
 * Blume sizes each preview from a line-count estimate and then tweens to the real height,
 * which shoves the page around on every navigation. Applying these up front avoids that.
 * Missing or stale entries are harmless: Blume still settles to the measured height.
 */
export const EXAMPLE_HEIGHTS: Record<string, number> = {
  "button/examples/button-sizes": 176,
  "button/examples/button-variants": 172,
  "chatgpt/examples/chatgpt-actions": 130,
  "chatgpt/examples/chatgpt-activity": 118,
  "chatgpt/examples/chatgpt-composer": 326,
  "chatgpt/examples/chatgpt-demo": 648,
  "chatgpt/examples/chatgpt-message": 278,
  "chatgpt/examples/chatgpt-model-selector": 254,
  "chatgpt/examples/chatgpt-reasoning": 178,
  "chatgpt/examples/chatgpt-search": 182,
  "chatgpt/examples/chatgpt-source-chip": 222,
  "chatgpt/examples/chatgpt-thinking": 126,
  "chatgpt/examples/chatgpt-thread": 432,
  "claude/examples/claude-actions": 176,
  "claude/examples/claude-composer": 368,
  "claude/examples/claude-message": 295,
  "claude/examples/claude-model-selector": 396,
  "claude/examples/claude-plus-menu": 360,
  "claude/examples/claude-search": 126,
  "claude/examples/claude-sources": 227,
  "claude/examples/claude-spinner": 128,
  "claude/examples/claude-thinking": 120,
  "claude/examples/claude-tool-calls": 264,
  "gemini/examples/gemini-actions": 287,
  "gemini/examples/gemini-composer": 178,
  "gemini/examples/gemini-demo": 648,
  "gemini/examples/gemini-message": 301,
  "gemini/examples/gemini-model-selector": 406,
  "gemini/examples/gemini-source-chip": 189,
  "gemini/examples/gemini-sparkle": 170,
  "gemini/examples/gemini-thinking": 178,
  "gemini/examples/gemini-thoughts": 312,
  "google-ai-overview/examples/ai-overview-citation": 200,
  "google-ai-overview/examples/ai-overview-content": 260,
  "google-ai-overview/examples/ai-overview-header": 176,
  "google-ai-overview/examples/ai-overview-highlight": 168,
  "google-ai-overview/examples/ai-overview-skeleton": 236,
  "google-ai-overview/examples/google-ai-overview-preview": 631,
  "marketing-button/examples/marketing-button-demo": 156,
  "marketing-button/examples/marketing-button-link": 156,
  "marketing-button/examples/marketing-button-primary": 156,
  "marketing-button/examples/marketing-button-secondary": 156,
  "opencode/examples/opencode-activity": 212,
  "opencode/examples/opencode-composer": 257,
  "opencode/examples/opencode-demo": 648,
  "opencode/examples/opencode-logo": 406,
  "opencode/examples/opencode-message": 288,
  "opencode/examples/opencode-sidebar": 423,
  "opencode/examples/opencode-sources": 259,
  "opencode/examples/opencode-window": 155,
  "perplexity/examples/perplexity-actions": 128,
  "perplexity/examples/perplexity-citation": 174,
  "perplexity/examples/perplexity-composer": 198,
  "perplexity/examples/perplexity-demo": 648,
  "perplexity/examples/perplexity-favicon": 120,
  "perplexity/examples/perplexity-message": 216,
  "perplexity/examples/perplexity-model-icon": 112,
  "perplexity/examples/perplexity-model-selector": 200,
  "perplexity/examples/perplexity-rewrite-panel": 529,
  "perplexity/examples/perplexity-search": 285,
  "perplexity/examples/perplexity-sources-summary": 128,
  "perplexity/examples/perplexity-thinking": 116,
  "perplexity/examples/perplexity-user-actions": 140,
  "shimmer/examples/shimmer": 148,
};
