export const INGEST_MAX_BODY_BYTES = 64 * 1024;
export const INGEST_DEFAULT_PORT = 3101;
export const INGEST_REQUIRED_ENV = [
  "DATABASE_URL",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "TINYBIRD_TOKEN",
] as const;
