import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";

export default defineConfig({
  extends: [core, react, next],
  ignorePatterns: [
    ...core.ignorePatterns,
    "packages/ui/src/**",
    ".agents/skills/**",
    "apps/dashboard/src/components/evilcharts/**",
    "packages/db/migrations/**",
    ".temp/**",
    "**/*.astro",
  ],
  options: {
    reportUnusedDisableDirectives: "warn",
  },
  // Keep the full presets as the source of truth while baselining rules that
  // conflict with existing code. Newly added Ultracite rules stay enabled.
  rules: {
    "arrow-body-style": "off",
    "class-methods-use-this": "off",
    complexity: "off",
    eqeqeq: "off",
    "func-names": "off",
    "func-style": "off",
    "logical-assignment-operators": "off",
    "max-classes-per-file": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-div-regex": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-inline-comments": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "warn",
    "no-new": "off",
    "no-plusplus": "off",
    "no-promise-executor-return": "off",
    "no-shadow": "off",
    "no-unused-vars": "off",
    "no-use-before-define": "off",
    "no-useless-return": "off",
    "no-warning-comments": "off",
    "prefer-arrow-callback": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "preserve-caught-error": "off",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "import/consistent-type-specifier-style": "off",
    "import/first": "off",
    "import/newline-after-import": "off",
    "import/no-cycle": "off",
    "import/no-named-as-default": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/interactive-supports-focus": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    "nextjs/no-img-element": "off",
    "node/callback-return": "off",
    "oxc/branches-sharing-code": "off",
    "oxc/no-accumulating-spread": "off",
    "promise/avoid-new": "off",
    "promise/no-promise-in-callback": "off",
    "promise/no-return-wrap": "off",
    "promise/param-names": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "react/button-has-type": "off",
    "react/capitalized-calls": "off",
    "react/exhaustive-effect-dependencies": "off",
    "react/function-component-definition": "off",
    "react/hook-use-state": "off",
    "react/immutability": "off",
    "react/incompatible-library": "off",
    "react/jsx-handler-names": "off",
    "react/memo-dependencies": "off",
    "react/jsx-no-constructed-context-values": "off",
    "react/jsx-no-target-blank": "off",
    "react/jsx-no-useless-fragment": "off",
    "react/jsx-pascal-case": "off",
    "react/no-danger": "off",
    "react/no-deriving-state-in-effects": "off",
    "react/no-object-type-as-default-prop": "off",
    "react/no-react-children": "off",
    "react/no-unescaped-entities": "off",
    "react/no-unstable-nested-components": "off",
    "react/prefer-function-component": "off",
    "react/preserve-manual-memoization": "off",
    "react/refs": "off",
    "react/set-state-in-effect": "off",
    "react/todo": "off",
    "react/exhaustive-deps": "warn",
    "react/rules-of-hooks": "off",
    "typescript/array-type": "off",
    "typescript/consistent-generic-constructors": "off",
    "typescript/consistent-indexed-object-style": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/consistent-type-imports": "off",
    "typescript/method-signature-style": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-empty-interface": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-invalid-void-type": "off",
    "typescript/no-non-null-assertion": "warn",
    "unicorn/catch-error-name": "off",
    "unicorn/consistent-existence-index-check": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/custom-error-definition": "off",
    "unicorn/escape-case": "off",
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-array-reduce": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-document-cookie": "off",
    "unicorn/no-immediate-mutation": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-new-array": "off",
    "unicorn/no-object-as-default-parameter": "off",
    "unicorn/no-thenable": "off",
    "unicorn/no-unreadable-array-destructuring": "off",
    "unicorn/no-useless-collection-argument": "off",
    "unicorn/no-useless-fallback-in-spread": "off",
    "unicorn/no-useless-spread": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/no-zero-fractions": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/prefer-array-find": "off",
    "unicorn/prefer-code-point": "off",
    "unicorn/prefer-dom-node-append": "off",
    "unicorn/prefer-dom-node-dataset": "off",
    "unicorn/prefer-dom-node-remove": "off",
    "unicorn/prefer-dom-node-text-content": "off",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-import-meta-properties": "off",
    "unicorn/prefer-logical-operator-over-ternary": "off",
    "unicorn/prefer-modern-math-apis": "off",
    "unicorn/prefer-module": "off",
    "unicorn/prefer-native-coercion-functions": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/prefer-optional-catch-binding": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-regexp-test": "off",
    "unicorn/prefer-response-static-json": "off",
    "unicorn/prefer-set-has": "off",
    "unicorn/prefer-single-call": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/prefer-string-slice": "off",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-type-error": "off",
    "unicorn/require-array-join-separator": "off",
    "unicorn/switch-case-braces": "off",
    "unicorn/text-encoding-identifier-case": "off",
  },
  overrides: [
    {
      // Effect's TaggedError is a curried schema class factory, not an Error constructor.
      files: [
        "apps/agent/agent/lib/schemas/chat-mirror.ts",
        "apps/agent/agent/lib/schemas/slack.ts",
        "packages/schemas/src/schemas/dashboard/onboarding-agent.ts",
        "packages/schemas/src/schemas/api/internal-dashboard.ts",
        "packages/schemas/src/schemas/api/qstash.ts",
        "packages/ai/src/integrations/mcp-auth-errors.ts",
        "packages/ai/src/integrations/mcp-oauth-errors.ts",
        "packages/ai/src/schemas/slack.ts",
        "packages/ai/src/schemas/github-operations.ts",
        "packages/tools/src/schemas/retry.ts",
        "packages/tools/src/schemas/social.ts",
      ],
      rules: {
        "unicorn/throw-new-error": "off",
      },
    },
    {
      files: ["packages/geo/src/index.ts", "packages/geo/src/feedback.ts"],
      rules: {
        "oxc/no-barrel-file": "off",
      },
    },
    {
      // Every Autumn customer read must go through the shared wrapper, or it
      // requests a differently-shaped `expand` and gets its own cache entry.
      files: ["apps/dashboard/src/**"],
      rules: {
        "no-restricted-imports": [
          "error",
          {
            paths: [
              {
                name: "autumn-js/react",
                importNames: ["useCustomer"],
                message:
                  "Import useBillingCustomer from @/lib/hooks/use-billing-customer instead, so all callers share one customer query.",
              },
            ],
          },
        ],
      },
    },
    {
      files: [
        "apps/dashboard/src/lib/hooks/use-billing-customer.ts",
        "apps/dashboard/src/utils/billing-customer.ts",
        "apps/dashboard/src/types/billing/plan.ts",
      ],
      rules: {
        "no-restricted-imports": "off",
      },
    },
  ],
});
