import { UTILITY_MODEL_ID } from "@notra/ai/constants/models";

export const FEEDBACK_CLASSIFIER_MODEL_ID = UTILITY_MODEL_ID;
export const FEEDBACK_CLASSIFIER_TIMEOUT_MS = 6000;
export const FEEDBACK_CLASSIFIER_MAX_MESSAGE_CHARS = 4000;
export const FEEDBACK_CLASSIFIER_FEATURE = "agent_feedback_classifier";
export const FEEDBACK_CLASSIFIER_REASONING_EFFORT = "low";
export const FEEDBACK_CLASSIFIER_TITLE_MAX_LENGTH = 80;
