export const SITE_NAME_MODERATION_FEATURE = "site_name_moderation";

export const SITE_NAME_MODERATION_TIMEOUT_MS = 3000;

export const SITE_NAME_OFFENSIVE_THRESHOLD = 0.7;

export const SITE_NAME_IMPERSONATION_THRESHOLD = 0.8;
