import {
  Activity01Icon,
  AiBrowserIcon,
  AiChat01Icon,
  Analytics01Icon,
  AnalyticsUpIcon,
  Calendar03Icon,
  ChartAnalysisIcon,
  Comment01Icon,
  CorporateIcon,
  CreditCardIcon,
  Home01Icon,
  Key01Icon,
  Layers01Icon,
  Message01Icon,
  NoteIcon,
  Notification03Icon,
  PencilEdit01Icon,
  PlugIcon,
  SearchList01Icon,
  Settings01Icon,
  UserCircleIcon,
  UserGroupIcon,
  Wallet01Icon,
} from "@hugeicons/core-free-icons";

import type {
  CommandRoute,
  CommandSection,
} from "@/types/components/command-palette";

export type {
  CommandRoute,
  CommandSection,
} from "@/types/components/command-palette";

export const COMMAND_ROUTES: CommandRoute[] = [
  {
    id: "home",
    label: "Home",
    keywords: ["dashboard", "start", "overview"],
    icon: Home01Icon,
    section: "Navigation",
    path: (slug) => `/${slug}`,
  },
  {
    id: "chat",
    label: "Chat",
    keywords: ["ai", "assistant", "conversation", "message"],
    icon: Message01Icon,
    section: "Navigation",
    path: (slug) => `/${slug}/chat`,
  },
  {
    id: "analytics",
    label: "Analytics",
    keywords: ["stats", "metrics", "followers", "engagement", "social"],
    icon: Analytics01Icon,
    section: "Navigation",
    path: (slug) => `/${slug}/analytics`,
  },
  {
    id: "geo",
    label: "Overview",
    keywords: ["geo", "ai", "mentions", "visibility", "chatgpt"],
    icon: AiBrowserIcon,
    section: "GEO",
    path: (slug) => `/${slug}/geo`,
  },
  {
    id: "geo-traffic",
    label: "Traffic",
    keywords: [
      "geo",
      "ai",
      "traffic",
      "crawlers",
      "referrals",
      "visits",
      "citations",
      "bots",
    ],
    icon: Activity01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/traffic`,
  },
  {
    id: "geo-prompts",
    label: "Prompts",
    keywords: ["geo", "ai", "prompts", "questions", "tracking"],
    icon: AiChat01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/prompts`,
  },
  {
    id: "geo-personas",
    label: "Personas",
    keywords: [
      "geo",
      "ai",
      "personas",
      "buyers",
      "icp",
      "customer profiles",
      "memories",
    ],
    icon: UserGroupIcon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/personas`,
  },
  {
    id: "geo-gaps",
    label: "Content Gaps",
    keywords: [
      "geo",
      "ai",
      "gaps",
      "content gap",
      "write",
      "opportunity",
      "mentions",
    ],
    icon: SearchList01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/gaps`,
  },
  {
    id: "geo-shelf-space",
    label: "Shelf Space",
    keywords: [
      "geo",
      "ai",
      "shelf",
      "shelf space",
      "citations",
      "sources",
      "backlinks",
      "listicle",
      "opportunity",
      "ticket",
    ],
    icon: Layers01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/shelf-space`,
  },
  {
    id: "geo-competitors",
    label: "Competitors",
    keywords: ["geo", "ai", "competitors", "share of voice", "brands"],
    icon: ChartAnalysisIcon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/competitors`,
  },
  {
    id: "geo-write",
    label: "Write",
    keywords: ["geo", "ai", "write", "writer", "article", "blog", "brief"],
    icon: PencilEdit01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/write`,
  },
  {
    id: "geo-settings",
    label: "Settings",
    keywords: [
      "geo",
      "ai",
      "settings",
      "tracking",
      "models",
      "languages",
      "aliases",
    ],
    icon: Settings01Icon,
    section: "GEO",
    path: (slug) => `/${slug}/geo/settings`,
  },
  {
    id: "content",
    label: "Content",
    keywords: ["posts", "drafts", "notes", "articles"],
    icon: NoteIcon,
    section: "Workspace",
    path: (slug) => `/${slug}/content`,
  },
  {
    id: "brand-company-info",
    label: "Company Info",
    keywords: ["brand", "identity", "voice", "tone", "company"],
    icon: CorporateIcon,
    section: "Workspace",
    path: (slug) => `/${slug}/brand/identity`,
  },
  {
    id: "brand-references",
    label: "References",
    keywords: ["brand", "identity", "references", "examples", "posts"],
    icon: Comment01Icon,
    section: "Workspace",
    path: (slug) => `/${slug}/brand/identity?view=references`,
  },
  {
    id: "automation-schedules",
    label: "Schedules",
    keywords: ["cron", "recurring", "automation", "calendar"],
    icon: Calendar03Icon,
    section: "Automation",
    path: (slug) => `/${slug}/automation/schedules`,
  },
  {
    id: "automation-events",
    label: "Events",
    keywords: ["triggers", "webhooks", "automation"],
    icon: Notification03Icon,
    section: "Automation",
    path: (slug) => `/${slug}/automation/events`,
  },
  {
    id: "api-keys",
    label: "API Keys",
    keywords: ["tokens", "secrets", "credentials", "auth"],
    icon: Key01Icon,
    section: "Manage",
    path: (slug) => `/${slug}/api-keys`,
  },
  {
    id: "integrations",
    label: "Integrations",
    keywords: ["github", "linear", "framer", "raycast", "connect"],
    icon: PlugIcon,
    section: "Manage",
    path: (slug) => `/${slug}/integrations`,
  },
  {
    id: "logs",
    label: "Logs",
    keywords: ["audit", "activity", "events", "history"],
    icon: AnalyticsUpIcon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/logs`,
  },
  {
    id: "settings-account",
    label: "Account",
    keywords: ["profile", "user", "email", "password"],
    icon: UserCircleIcon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/account`,
  },
  {
    id: "settings-general",
    label: "General Settings",
    keywords: ["organization", "workspace", "name", "logo"],
    icon: Settings01Icon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/general`,
  },
  {
    id: "settings-members",
    label: "Members",
    keywords: ["team", "users", "invite", "people"],
    icon: UserGroupIcon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/members`,
  },
  {
    id: "settings-notifications",
    label: "Notifications",
    keywords: ["alerts", "email", "preferences"],
    icon: Notification03Icon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/notifications`,
  },
  {
    id: "settings-billing",
    label: "Billing & Usage",
    keywords: ["subscription", "plan", "invoice", "payment"],
    icon: CreditCardIcon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/billing`,
  },
  {
    id: "settings-credits",
    label: "Credits",
    keywords: ["balance", "top up", "tokens", "ai"],
    icon: Wallet01Icon,
    section: "Settings",
    path: (slug) => `/${slug}/settings/credits`,
    requiresAiCredits: true,
  },
];

export const COMMAND_SECTIONS: CommandSection[] = [
  "Navigation",
  "GEO",
  "Workspace",
  "Automation",
  "Manage",
  "Settings",
];

export function isCommandRouteAvailable(
  route: CommandRoute,
  hasAiCredits: boolean
): boolean {
  return !route.requiresAiCredits || hasAiCredits;
}

export function commandRoutesForAI(slug: string, hasAiCredits: boolean) {
  return COMMAND_ROUTES.filter((r) =>
    isCommandRouteAvailable(r, hasAiCredits)
  ).map((r) => ({
    id: r.id,
    label: r.label,
    path: r.path(slug),
    keywords: r.keywords,
  }));
}
