/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as FeedbackDotmdRouteImport } from './routes/feedback[.]md'
import { Route as IpCheckerDotmdRouteImport } from './routes/ip-checker[.]md'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SchemaMapDotxmlRouteImport } from './routes/schema-map[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known/agent-card[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownHttpMessageSignaturesDirectoryRouteImport } from './routes/[.]well-known/http-message-signatures-directory'
import { Route as DotwellKnownIntegrationsDotjsonRouteImport } from './routes/[.]well-known/integrations[.]json'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingHomeRouteImport } from './routes/_landing/home'
import { Route as LandingLandingRouteImport } from './routes/_landing/landing'
import { Route as SiteBlogRouteImport } from './routes/_site/_blog'
import { Route as SiteChangelogRouteImport } from './routes/_site/_changelog'
import { Route as SiteLegalRouteImport } from './routes/_site/_legal'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteAgentRouteImport } from './routes/_site/agent'
import { Route as SiteBrandRouteImport } from './routes/_site/brand'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteFeedbackMdRouteImport } from './routes/_site/feedback-md'
import { Route as SiteFreeHatRouteImport } from './routes/_site/free-hat'
import { Route as SiteHtmlToFigmaRouteImport } from './routes/_site/html-to-figma'
import { Route as SiteHtmlToPaperRouteImport } from './routes/_site/html-to-paper'
import { Route as SiteIpCheckerRouteImport } from './routes/_site/ip-checker'
import { Route as SiteOssProgramRouteImport } from './routes/_site/oss-program'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SiteRepoStarVideoRouteImport } from './routes/_site/repo-star-video'
import { Route as SiteTwitterThreadCreatorRouteImport } from './routes/_site/twitter-thread-creator'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiIpCheckerRouteImport } from './routes/api/ip-checker'
import { Route as ApiLlmsDottxtRouteImport } from './routes/api/llms[.]txt'
import { Route as ApiOssProgramRouteImport } from './routes/api/oss-program'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as DevelopersLlmsDottxtRouteImport } from './routes/developers/llms[.]txt'
import { Route as MarketingChatRouteImport } from './routes/marketing/chat'
import { Route as MdSplatRouteImport } from './routes/md/$'
import { Route as SchemaNotraDotjsonlRouteImport } from './routes/schema/notra[.]jsonl'
import { Route as V1IndexRouteImport } from './routes/v1/index'
import { Route as V1StatusRouteImport } from './routes/v1/status'
import { Route as DotwellKnownMcpIndexRouteImport } from './routes/[.]well-known/mcp/index'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as SiteLegalLegalRouteImport } from './routes/_site/_legal/legal'
import { Route as SiteLegalPrivacyRouteImport } from './routes/_site/_legal/privacy'
import { Route as SiteLegalTermsRouteImport } from './routes/_site/_legal/terms'
import { Route as SiteCompareIndexRouteImport } from './routes/_site/compare/index'
import { Route as SiteContributorsIndexRouteImport } from './routes/_site/contributors/index'
import { Route as SiteContributorsOpengraphImageRouteImport } from './routes/_site/contributors/opengraph-image'
import { Route as SiteFeaturesIndexRouteImport } from './routes/_site/features/index'
import { Route as SiteFeaturesAiCrawlerLogsRouteImport } from './routes/_site/features/ai-crawler-logs'
import { Route as SiteFeaturesConversationsRouteImport } from './routes/_site/features/conversations'
import { Route as SiteFeaturesPersonasRouteImport } from './routes/_site/features/personas'
import { Route as SiteIntegrationsIndexRouteImport } from './routes/_site/integrations/index'
import { Route as SiteIntegrationsIdRouteImport } from './routes/_site/integrations/$id'
import { Route as SiteIntegrationsGithubRouteImport } from './routes/_site/integrations/github'
import { Route as SiteIntegrationsGranolaRouteImport } from './routes/_site/integrations/granola'
import { Route as SiteIntegrationsLinearRouteImport } from './routes/_site/integrations/linear'
import { Route as SiteIntegrationsSlackRouteImport } from './routes/_site/integrations/slack'
import { Route as SiteMcpIndexRouteImport } from './routes/_site/mcp/index'
import { Route as SiteNotraVsChar123slugChar125IndexRouteImport } from './routes/_site/notra-vs-{$slug}/index'
import { Route as SiteNotraVsChar123slugChar125OpengraphImageRouteImport } from './routes/_site/notra-vs-{$slug}/opengraph-image'
import { Route as SiteOfferingIndexRouteImport } from './routes/_site/offering/index'
import { Route as SiteOfferingReportRouteImport } from './routes/_site/offering/report'
import { Route as SiteStateOfAiSearchIndexRouteImport } from './routes/_site/state-of-ai-search/index'
import { Route as AgentAuthAuthorizeRouteImport } from './routes/agent/auth/authorize'
import { Route as AgentAuthClaimRouteImport } from './routes/agent/auth/claim'
import { Route as AgentAuthRegisterRouteImport } from './routes/agent/auth/register'
import { Route as AgentAuthRevokeRouteImport } from './routes/agent/auth/revoke'
import { Route as AgentAuthTokenRouteImport } from './routes/agent/auth/token'
import { Route as ApiC15tSplatRouteImport } from './routes/api/c15t/$'
import { Route as ApiOfferingCheckIndexRouteImport } from './routes/api/offering-check/index'
import { Route as ApiOfferingCheckPreflightRouteImport } from './routes/api/offering-check/preflight'
import { Route as ApiStarVideoRenderRouteImport } from './routes/api/star-video/render'
import { Route as ApiStarVideoRepoRouteImport } from './routes/api/star-video/repo'
import { Route as SiteBlogBlogIndexRouteImport } from './routes/_site/_blog/blog/index'
import { Route as SiteChangelogChangelogIndexRouteImport } from './routes/_site/_changelog/changelog/index'
import { Route as SiteFeaturesMarketingAssetsRouteImport } from './routes/_site/features/marketing/assets'
import { Route as SiteMcpUseCasesIndexRouteImport } from './routes/_site/mcp/use-cases/index'
import { Route as SiteMcpUseCasesSlugRouteImport } from './routes/_site/mcp/use-cases/$slug'
import { Route as SiteStateOfAiSearchCategoryIndexRouteImport } from './routes/_site/state-of-ai-search/$category/index'
import { Route as ApiStarVideoGithubAuthorizeRouteImport } from './routes/api/star-video/github/authorize'
import { Route as ApiStarVideoGithubCallbackRouteImport } from './routes/api/star-video/github/callback'
import { Route as SiteBlogBlogSlugIndexRouteImport } from './routes/_site/_blog/blog/$slug/index'
import { Route as SiteBlogBlogSlugOpengraphImageRouteImport } from './routes/_site/_blog/blog/$slug/opengraph-image'
import { Route as SiteChangelogChangelogNameIndexRouteImport } from './routes/_site/_changelog/changelog/$name/index'
import { Route as SiteChangelogChangelogNameSlugRouteImport } from './routes/_site/_changelog/changelog/$name/$slug'
import { Route as SiteChangelogChangelogNotraIndexRouteImport } from './routes/_site/_changelog/changelog/notra/index'
import { Route as SiteChangelogChangelogNotraSlugRouteImport } from './routes/_site/_changelog/changelog/notra/$slug'
import { Route as SiteStateOfAiSearchCategoryEditionIndexRouteImport } from './routes/_site/state-of-ai-search/$category/$edition/index'
import { Route as SiteStateOfAiSearchCategoryEditionDataDotcsvRouteImport } from './routes/_site/state-of-ai-search/$category/$edition/data[.]csv'
import { Route as SiteStateOfAiSearchCategoryEditionOpengraphImageRouteImport } from './routes/_site/state-of-ai-search/$category/$edition/opengraph-image'
import { Route as SiteBlogBlogAuthorSlugIndexRouteImport } from './routes/_site/_blog/blog/author/$slug/index'
import { Route as SiteBlogBlogAuthorSlugOpengraphImageRouteImport } from './routes/_site/_blog/blog/author/$slug/opengraph-image'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackDotmdRoute = FeedbackDotmdRouteImport.update({
  id: '/feedback.md',
  path: '/feedback.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IpCheckerDotmdRoute = IpCheckerDotmdRouteImport.update({
  id: '/ip-checker.md',
  path: '/ip-checker.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaMapDotxmlRoute = SchemaMapDotxmlRouteImport.update({
  id: '/schema-map.xml',
  path: '/schema-map.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownHttpMessageSignaturesDirectoryRoute =
  DotwellKnownHttpMessageSignaturesDirectoryRouteImport.update({
    id: '/.well-known/http-message-signatures-directory',
    path: '/.well-known/http-message-signatures-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownIntegrationsDotjsonRoute =
  DotwellKnownIntegrationsDotjsonRouteImport.update({
    id: '/.well-known/integrations.json',
    path: '/.well-known/integrations.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingHomeRoute = LandingHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LandingRoute,
} as any)
const LandingLandingRoute = LandingLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => LandingRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/_blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChangelogRoute = SiteChangelogRouteImport.update({
  id: '/_changelog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLegalRoute = SiteLegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAgentRoute = SiteAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBrandRoute = SiteBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeedbackMdRoute = SiteFeedbackMdRouteImport.update({
  id: '/feedback-md',
  path: '/feedback-md',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFreeHatRoute = SiteFreeHatRouteImport.update({
  id: '/free-hat',
  path: '/free-hat',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHtmlToFigmaRoute = SiteHtmlToFigmaRouteImport.update({
  id: '/html-to-figma',
  path: '/html-to-figma',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHtmlToPaperRoute = SiteHtmlToPaperRouteImport.update({
  id: '/html-to-paper',
  path: '/html-to-paper',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIpCheckerRoute = SiteIpCheckerRouteImport.update({
  id: '/ip-checker',
  path: '/ip-checker',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOssProgramRoute = SiteOssProgramRouteImport.update({
  id: '/oss-program',
  path: '/oss-program',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRepoStarVideoRoute = SiteRepoStarVideoRouteImport.update({
  id: '/repo-star-video',
  path: '/repo-star-video',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTwitterThreadCreatorRoute =
  SiteTwitterThreadCreatorRouteImport.update({
    id: '/twitter-thread-creator',
    path: '/twitter-thread-creator',
    getParentRoute: () => SiteRoute,
  } as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpCheckerRoute = ApiIpCheckerRouteImport.update({
  id: '/api/ip-checker',
  path: '/api/ip-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsDottxtRoute = ApiLlmsDottxtRouteImport.update({
  id: '/api/llms.txt',
  path: '/api/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOssProgramRoute = ApiOssProgramRouteImport.update({
  id: '/api/oss-program',
  path: '/api/oss-program',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersLlmsDottxtRoute = DevelopersLlmsDottxtRouteImport.update({
  id: '/developers/llms.txt',
  path: '/developers/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingChatRoute = MarketingChatRouteImport.update({
  id: '/marketing/chat',
  path: '/marketing/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MdSplatRoute = MdSplatRouteImport.update({
  id: '/md/$',
  path: '/md/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaNotraDotjsonlRoute = SchemaNotraDotjsonlRouteImport.update({
  id: '/schema/notra.jsonl',
  path: '/schema/notra.jsonl',
  getParentRoute: () => rootRouteImport,
} as any)
const V1IndexRoute = V1IndexRouteImport.update({
  id: '/v1/',
  path: '/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StatusRoute = V1StatusRouteImport.update({
  id: '/v1/status',
  path: '/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpIndexRoute = DotwellKnownMcpIndexRouteImport.update({
  id: '/.well-known/mcp/',
  path: '/.well-known/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteLegalLegalRoute = SiteLegalLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => SiteLegalRoute,
} as any)
const SiteLegalPrivacyRoute = SiteLegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteLegalRoute,
} as any)
const SiteLegalTermsRoute = SiteLegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteLegalRoute,
} as any)
const SiteCompareIndexRoute = SiteCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContributorsIndexRoute = SiteContributorsIndexRouteImport.update({
  id: '/contributors/',
  path: '/contributors/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContributorsOpengraphImageRoute =
  SiteContributorsOpengraphImageRouteImport.update({
    id: '/contributors/opengraph-image',
    path: '/contributors/opengraph-image',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteFeaturesIndexRoute = SiteFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesAiCrawlerLogsRoute =
  SiteFeaturesAiCrawlerLogsRouteImport.update({
    id: '/features/ai-crawler-logs',
    path: '/features/ai-crawler-logs',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteFeaturesConversationsRoute =
  SiteFeaturesConversationsRouteImport.update({
    id: '/features/conversations',
    path: '/features/conversations',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteFeaturesPersonasRoute = SiteFeaturesPersonasRouteImport.update({
  id: '/features/personas',
  path: '/features/personas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsIndexRoute = SiteIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsIdRoute = SiteIntegrationsIdRouteImport.update({
  id: '/integrations/$id',
  path: '/integrations/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsGithubRoute = SiteIntegrationsGithubRouteImport.update({
  id: '/integrations/github',
  path: '/integrations/github',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsGranolaRoute = SiteIntegrationsGranolaRouteImport.update({
  id: '/integrations/granola',
  path: '/integrations/granola',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsLinearRoute = SiteIntegrationsLinearRouteImport.update({
  id: '/integrations/linear',
  path: '/integrations/linear',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsSlackRoute = SiteIntegrationsSlackRouteImport.update({
  id: '/integrations/slack',
  path: '/integrations/slack',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMcpIndexRoute = SiteMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNotraVsChar123slugChar125IndexRoute =
  SiteNotraVsChar123slugChar125IndexRouteImport.update({
    id: '/notra-vs-{$slug}/',
    path: '/notra-vs-{$slug}/',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteNotraVsChar123slugChar125OpengraphImageRoute =
  SiteNotraVsChar123slugChar125OpengraphImageRouteImport.update({
    id: '/notra-vs-{$slug}/opengraph-image',
    path: '/notra-vs-{$slug}/opengraph-image',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteOfferingIndexRoute = SiteOfferingIndexRouteImport.update({
  id: '/offering/',
  path: '/offering/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOfferingReportRoute = SiteOfferingReportRouteImport.update({
  id: '/offering/report',
  path: '/offering/report',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStateOfAiSearchIndexRoute =
  SiteStateOfAiSearchIndexRouteImport.update({
    id: '/state-of-ai-search/',
    path: '/state-of-ai-search/',
    getParentRoute: () => SiteRoute,
  } as any)
const AgentAuthAuthorizeRoute = AgentAuthAuthorizeRouteImport.update({
  id: '/agent/auth/authorize',
  path: '/agent/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuthClaimRoute = AgentAuthClaimRouteImport.update({
  id: '/agent/auth/claim',
  path: '/agent/auth/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuthRegisterRoute = AgentAuthRegisterRouteImport.update({
  id: '/agent/auth/register',
  path: '/agent/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuthRevokeRoute = AgentAuthRevokeRouteImport.update({
  id: '/agent/auth/revoke',
  path: '/agent/auth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAuthTokenRoute = AgentAuthTokenRouteImport.update({
  id: '/agent/auth/token',
  path: '/agent/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiC15tSplatRoute = ApiC15tSplatRouteImport.update({
  id: '/api/c15t/$',
  path: '/api/c15t/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfferingCheckIndexRoute = ApiOfferingCheckIndexRouteImport.update({
  id: '/api/offering-check/',
  path: '/api/offering-check/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfferingCheckPreflightRoute =
  ApiOfferingCheckPreflightRouteImport.update({
    id: '/api/offering-check/preflight',
    path: '/api/offering-check/preflight',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStarVideoRenderRoute = ApiStarVideoRenderRouteImport.update({
  id: '/api/star-video/render',
  path: '/api/star-video/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStarVideoRepoRoute = ApiStarVideoRepoRouteImport.update({
  id: '/api/star-video/repo',
  path: '/api/star-video/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBlogBlogIndexRoute = SiteBlogBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteChangelogChangelogIndexRoute =
  SiteChangelogChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => SiteChangelogRoute,
  } as any)
const SiteFeaturesMarketingAssetsRoute =
  SiteFeaturesMarketingAssetsRouteImport.update({
    id: '/features/marketing/assets',
    path: '/features/marketing/assets',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteMcpUseCasesIndexRoute = SiteMcpUseCasesIndexRouteImport.update({
  id: '/mcp/use-cases/',
  path: '/mcp/use-cases/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMcpUseCasesSlugRoute = SiteMcpUseCasesSlugRouteImport.update({
  id: '/mcp/use-cases/$slug',
  path: '/mcp/use-cases/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStateOfAiSearchCategoryIndexRoute =
  SiteStateOfAiSearchCategoryIndexRouteImport.update({
    id: '/state-of-ai-search/$category/',
    path: '/state-of-ai-search/$category/',
    getParentRoute: () => SiteRoute,
  } as any)
const ApiStarVideoGithubAuthorizeRoute =
  ApiStarVideoGithubAuthorizeRouteImport.update({
    id: '/api/star-video/github/authorize',
    path: '/api/star-video/github/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStarVideoGithubCallbackRoute =
  ApiStarVideoGithubCallbackRouteImport.update({
    id: '/api/star-video/github/callback',
    path: '/api/star-video/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteBlogBlogSlugIndexRoute = SiteBlogBlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteBlogBlogSlugOpengraphImageRoute =
  SiteBlogBlogSlugOpengraphImageRouteImport.update({
    id: '/blog/$slug/opengraph-image',
    path: '/blog/$slug/opengraph-image',
    getParentRoute: () => SiteBlogRoute,
  } as any)
const SiteChangelogChangelogNameIndexRoute =
  SiteChangelogChangelogNameIndexRouteImport.update({
    id: '/changelog/$name/',
    path: '/changelog/$name/',
    getParentRoute: () => SiteChangelogRoute,
  } as any)
const SiteChangelogChangelogNameSlugRoute =
  SiteChangelogChangelogNameSlugRouteImport.update({
    id: '/changelog/$name/$slug',
    path: '/changelog/$name/$slug',
    getParentRoute: () => SiteChangelogRoute,
  } as any)
const SiteChangelogChangelogNotraIndexRoute =
  SiteChangelogChangelogNotraIndexRouteImport.update({
    id: '/changelog/notra/',
    path: '/changelog/notra/',
    getParentRoute: () => SiteChangelogRoute,
  } as any)
const SiteChangelogChangelogNotraSlugRoute =
  SiteChangelogChangelogNotraSlugRouteImport.update({
    id: '/changelog/notra/$slug',
    path: '/changelog/notra/$slug',
    getParentRoute: () => SiteChangelogRoute,
  } as any)
const SiteStateOfAiSearchCategoryEditionIndexRoute =
  SiteStateOfAiSearchCategoryEditionIndexRouteImport.update({
    id: '/state-of-ai-search/$category/$edition/',
    path: '/state-of-ai-search/$category/$edition/',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteStateOfAiSearchCategoryEditionDataDotcsvRoute =
  SiteStateOfAiSearchCategoryEditionDataDotcsvRouteImport.update({
    id: '/state-of-ai-search/$category/$edition/data.csv',
    path: '/state-of-ai-search/$category/$edition/data.csv',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteStateOfAiSearchCategoryEditionOpengraphImageRoute =
  SiteStateOfAiSearchCategoryEditionOpengraphImageRouteImport.update({
    id: '/state-of-ai-search/$category/$edition/opengraph-image',
    path: '/state-of-ai-search/$category/$edition/opengraph-image',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteBlogBlogAuthorSlugIndexRoute =
  SiteBlogBlogAuthorSlugIndexRouteImport.update({
    id: '/blog/author/$slug/',
    path: '/blog/author/$slug/',
    getParentRoute: () => SiteBlogRoute,
  } as any)
const SiteBlogBlogAuthorSlugOpengraphImageRoute =
  SiteBlogBlogAuthorSlugOpengraphImageRouteImport.update({
    id: '/blog/author/$slug/opengraph-image',
    path: '/blog/author/$slug/opengraph-image',
    getParentRoute: () => SiteBlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/ask': typeof AskRoute
  '/auth.md': typeof AuthDotmdRoute
  '/feedback.md': typeof FeedbackDotmdRoute
  '/ip-checker.md': typeof IpCheckerDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/schema-map.xml': typeof SchemaMapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/integrations.json': typeof DotwellKnownIntegrationsDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/home': typeof LandingHomeRoute
  '/landing': typeof LandingLandingRoute
  '/about': typeof SiteAboutRoute
  '/agent': typeof SiteAgentRoute
  '/brand': typeof SiteBrandRoute
  '/contact': typeof SiteContactRoute
  '/feedback-md': typeof SiteFeedbackMdRoute
  '/free-hat': typeof SiteFreeHatRoute
  '/html-to-figma': typeof SiteHtmlToFigmaRoute
  '/html-to-paper': typeof SiteHtmlToPaperRoute
  '/ip-checker': typeof SiteIpCheckerRoute
  '/oss-program': typeof SiteOssProgramRoute
  '/pricing': typeof SitePricingRoute
  '/repo-star-video': typeof SiteRepoStarVideoRoute
  '/twitter-thread-creator': typeof SiteTwitterThreadCreatorRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ip-checker': typeof ApiIpCheckerRoute
  '/api/llms.txt': typeof ApiLlmsDottxtRoute
  '/api/oss-program': typeof ApiOssProgramRoute
  '/api/status': typeof ApiStatusRoute
  '/api/v1': typeof ApiV1Route
  '/developers/llms.txt': typeof DevelopersLlmsDottxtRoute
  '/marketing/chat': typeof MarketingChatRoute
  '/md/$': typeof MdSplatRoute
  '/schema/notra.jsonl': typeof SchemaNotraDotjsonlRoute
  '/v1/status': typeof V1StatusRoute
  '/api/': typeof ApiIndexRoute
  '/v1/': typeof V1IndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/legal': typeof SiteLegalLegalRoute
  '/privacy': typeof SiteLegalPrivacyRoute
  '/terms': typeof SiteLegalTermsRoute
  '/contributors/opengraph-image': typeof SiteContributorsOpengraphImageRoute
  '/features/ai-crawler-logs': typeof SiteFeaturesAiCrawlerLogsRoute
  '/features/conversations': typeof SiteFeaturesConversationsRoute
  '/features/personas': typeof SiteFeaturesPersonasRoute
  '/integrations/$id': typeof SiteIntegrationsIdRoute
  '/integrations/github': typeof SiteIntegrationsGithubRoute
  '/integrations/granola': typeof SiteIntegrationsGranolaRoute
  '/integrations/linear': typeof SiteIntegrationsLinearRoute
  '/integrations/slack': typeof SiteIntegrationsSlackRoute
  '/notra-vs-{$slug}/opengraph-image': typeof SiteNotraVsChar123slugChar125OpengraphImageRoute
  '/offering/report': typeof SiteOfferingReportRoute
  '/agent/auth/authorize': typeof AgentAuthAuthorizeRoute
  '/agent/auth/claim': typeof AgentAuthClaimRoute
  '/agent/auth/register': typeof AgentAuthRegisterRoute
  '/agent/auth/revoke': typeof AgentAuthRevokeRoute
  '/agent/auth/token': typeof AgentAuthTokenRoute
  '/api/c15t/$': typeof ApiC15tSplatRoute
  '/api/offering-check/preflight': typeof ApiOfferingCheckPreflightRoute
  '/api/star-video/render': typeof ApiStarVideoRenderRoute
  '/api/star-video/repo': typeof ApiStarVideoRepoRoute
  '/.well-known/mcp/': typeof DotwellKnownMcpIndexRoute
  '/compare/': typeof SiteCompareIndexRoute
  '/contributors/': typeof SiteContributorsIndexRoute
  '/features/': typeof SiteFeaturesIndexRoute
  '/integrations/': typeof SiteIntegrationsIndexRoute
  '/mcp/': typeof SiteMcpIndexRoute
  '/notra-vs-{$slug}/': typeof SiteNotraVsChar123slugChar125IndexRoute
  '/offering/': typeof SiteOfferingIndexRoute
  '/state-of-ai-search/': typeof SiteStateOfAiSearchIndexRoute
  '/api/offering-check/': typeof ApiOfferingCheckIndexRoute
  '/features/marketing/assets': typeof SiteFeaturesMarketingAssetsRoute
  '/mcp/use-cases/$slug': typeof SiteMcpUseCasesSlugRoute
  '/api/star-video/github/authorize': typeof ApiStarVideoGithubAuthorizeRoute
  '/api/star-video/github/callback': typeof ApiStarVideoGithubCallbackRoute
  '/blog/': typeof SiteBlogBlogIndexRoute
  '/changelog/': typeof SiteChangelogChangelogIndexRoute
  '/mcp/use-cases/': typeof SiteMcpUseCasesIndexRoute
  '/state-of-ai-search/$category/': typeof SiteStateOfAiSearchCategoryIndexRoute
  '/blog/$slug/opengraph-image': typeof SiteBlogBlogSlugOpengraphImageRoute
  '/changelog/$name/$slug': typeof SiteChangelogChangelogNameSlugRoute
  '/changelog/notra/$slug': typeof SiteChangelogChangelogNotraSlugRoute
  '/state-of-ai-search/$category/$edition/data.csv': typeof SiteStateOfAiSearchCategoryEditionDataDotcsvRoute
  '/state-of-ai-search/$category/$edition/opengraph-image': typeof SiteStateOfAiSearchCategoryEditionOpengraphImageRoute
  '/blog/$slug/': typeof SiteBlogBlogSlugIndexRoute
  '/changelog/$name/': typeof SiteChangelogChangelogNameIndexRoute
  '/changelog/notra/': typeof SiteChangelogChangelogNotraIndexRoute
  '/state-of-ai-search/$category/$edition/': typeof SiteStateOfAiSearchCategoryEditionIndexRoute
  '/blog/author/$slug/opengraph-image': typeof SiteBlogBlogAuthorSlugOpengraphImageRoute
  '/blog/author/$slug/': typeof SiteBlogBlogAuthorSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/ask': typeof AskRoute
  '/auth.md': typeof AuthDotmdRoute
  '/feedback.md': typeof FeedbackDotmdRoute
  '/ip-checker.md': typeof IpCheckerDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/schema-map.xml': typeof SchemaMapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/integrations.json': typeof DotwellKnownIntegrationsDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/home': typeof LandingHomeRoute
  '/landing': typeof LandingLandingRoute
  '/about': typeof SiteAboutRoute
  '/agent': typeof SiteAgentRoute
  '/brand': typeof SiteBrandRoute
  '/contact': typeof SiteContactRoute
  '/feedback-md': typeof SiteFeedbackMdRoute
  '/free-hat': typeof SiteFreeHatRoute
  '/html-to-figma': typeof SiteHtmlToFigmaRoute
  '/html-to-paper': typeof SiteHtmlToPaperRoute
  '/ip-checker': typeof SiteIpCheckerRoute
  '/oss-program': typeof SiteOssProgramRoute
  '/pricing': typeof SitePricingRoute
  '/repo-star-video': typeof SiteRepoStarVideoRoute
  '/twitter-thread-creator': typeof SiteTwitterThreadCreatorRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ip-checker': typeof ApiIpCheckerRoute
  '/api/llms.txt': typeof ApiLlmsDottxtRoute
  '/api/oss-program': typeof ApiOssProgramRoute
  '/api/status': typeof ApiStatusRoute
  '/api/v1': typeof ApiV1Route
  '/developers/llms.txt': typeof DevelopersLlmsDottxtRoute
  '/marketing/chat': typeof MarketingChatRoute
  '/md/$': typeof MdSplatRoute
  '/schema/notra.jsonl': typeof SchemaNotraDotjsonlRoute
  '/v1/status': typeof V1StatusRoute
  '/api': typeof ApiIndexRoute
  '/v1': typeof V1IndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/legal': typeof SiteLegalLegalRoute
  '/privacy': typeof SiteLegalPrivacyRoute
  '/terms': typeof SiteLegalTermsRoute
  '/contributors/opengraph-image': typeof SiteContributorsOpengraphImageRoute
  '/features/ai-crawler-logs': typeof SiteFeaturesAiCrawlerLogsRoute
  '/features/conversations': typeof SiteFeaturesConversationsRoute
  '/features/personas': typeof SiteFeaturesPersonasRoute
  '/integrations/$id': typeof SiteIntegrationsIdRoute
  '/integrations/github': typeof SiteIntegrationsGithubRoute
  '/integrations/granola': typeof SiteIntegrationsGranolaRoute
  '/integrations/linear': typeof SiteIntegrationsLinearRoute
  '/integrations/slack': typeof SiteIntegrationsSlackRoute
  '/notra-vs-{$slug}/opengraph-image': typeof SiteNotraVsChar123slugChar125OpengraphImageRoute
  '/offering/report': typeof SiteOfferingReportRoute
  '/agent/auth/authorize': typeof AgentAuthAuthorizeRoute
  '/agent/auth/claim': typeof AgentAuthClaimRoute
  '/agent/auth/register': typeof AgentAuthRegisterRoute
  '/agent/auth/revoke': typeof AgentAuthRevokeRoute
  '/agent/auth/token': typeof AgentAuthTokenRoute
  '/api/c15t/$': typeof ApiC15tSplatRoute
  '/api/offering-check/preflight': typeof ApiOfferingCheckPreflightRoute
  '/api/star-video/render': typeof ApiStarVideoRenderRoute
  '/api/star-video/repo': typeof ApiStarVideoRepoRoute
  '/.well-known/mcp': typeof DotwellKnownMcpIndexRoute
  '/compare': typeof SiteCompareIndexRoute
  '/contributors': typeof SiteContributorsIndexRoute
  '/features': typeof SiteFeaturesIndexRoute
  '/integrations': typeof SiteIntegrationsIndexRoute
  '/mcp': typeof SiteMcpIndexRoute
  '/notra-vs-{$slug}': typeof SiteNotraVsChar123slugChar125IndexRoute
  '/offering': typeof SiteOfferingIndexRoute
  '/state-of-ai-search': typeof SiteStateOfAiSearchIndexRoute
  '/api/offering-check': typeof ApiOfferingCheckIndexRoute
  '/features/marketing/assets': typeof SiteFeaturesMarketingAssetsRoute
  '/mcp/use-cases/$slug': typeof SiteMcpUseCasesSlugRoute
  '/api/star-video/github/authorize': typeof ApiStarVideoGithubAuthorizeRoute
  '/api/star-video/github/callback': typeof ApiStarVideoGithubCallbackRoute
  '/blog': typeof SiteBlogBlogIndexRoute
  '/changelog': typeof SiteChangelogChangelogIndexRoute
  '/mcp/use-cases': typeof SiteMcpUseCasesIndexRoute
  '/state-of-ai-search/$category': typeof SiteStateOfAiSearchCategoryIndexRoute
  '/blog/$slug/opengraph-image': typeof SiteBlogBlogSlugOpengraphImageRoute
  '/changelog/$name/$slug': typeof SiteChangelogChangelogNameSlugRoute
  '/changelog/notra/$slug': typeof SiteChangelogChangelogNotraSlugRoute
  '/state-of-ai-search/$category/$edition/data.csv': typeof SiteStateOfAiSearchCategoryEditionDataDotcsvRoute
  '/state-of-ai-search/$category/$edition/opengraph-image': typeof SiteStateOfAiSearchCategoryEditionOpengraphImageRoute
  '/blog/$slug': typeof SiteBlogBlogSlugIndexRoute
  '/changelog/$name': typeof SiteChangelogChangelogNameIndexRoute
  '/changelog/notra': typeof SiteChangelogChangelogNotraIndexRoute
  '/state-of-ai-search/$category/$edition': typeof SiteStateOfAiSearchCategoryEditionIndexRoute
  '/blog/author/$slug/opengraph-image': typeof SiteBlogBlogAuthorSlugOpengraphImageRoute
  '/blog/author/$slug': typeof SiteBlogBlogAuthorSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/ask': typeof AskRoute
  '/auth.md': typeof AuthDotmdRoute
  '/feedback.md': typeof FeedbackDotmdRoute
  '/ip-checker.md': typeof IpCheckerDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/schema-map.xml': typeof SchemaMapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/integrations.json': typeof DotwellKnownIntegrationsDotjsonRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/_landing/home': typeof LandingHomeRoute
  '/_landing/landing': typeof LandingLandingRoute
  '/_site/_blog': typeof SiteBlogRouteWithChildren
  '/_site/_changelog': typeof SiteChangelogRouteWithChildren
  '/_site/_legal': typeof SiteLegalRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/agent': typeof SiteAgentRoute
  '/_site/brand': typeof SiteBrandRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/feedback-md': typeof SiteFeedbackMdRoute
  '/_site/free-hat': typeof SiteFreeHatRoute
  '/_site/html-to-figma': typeof SiteHtmlToFigmaRoute
  '/_site/html-to-paper': typeof SiteHtmlToPaperRoute
  '/_site/ip-checker': typeof SiteIpCheckerRoute
  '/_site/oss-program': typeof SiteOssProgramRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/repo-star-video': typeof SiteRepoStarVideoRoute
  '/_site/twitter-thread-creator': typeof SiteTwitterThreadCreatorRoute
  '/api/contact': typeof ApiContactRoute
  '/api/ip-checker': typeof ApiIpCheckerRoute
  '/api/llms.txt': typeof ApiLlmsDottxtRoute
  '/api/oss-program': typeof ApiOssProgramRoute
  '/api/status': typeof ApiStatusRoute
  '/api/v1': typeof ApiV1Route
  '/developers/llms.txt': typeof DevelopersLlmsDottxtRoute
  '/marketing/chat': typeof MarketingChatRoute
  '/md/$': typeof MdSplatRoute
  '/schema/notra.jsonl': typeof SchemaNotraDotjsonlRoute
  '/v1/status': typeof V1StatusRoute
  '/_landing/': typeof LandingIndexRoute
  '/api/': typeof ApiIndexRoute
  '/v1/': typeof V1IndexRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/_site/_legal/legal': typeof SiteLegalLegalRoute
  '/_site/_legal/privacy': typeof SiteLegalPrivacyRoute
  '/_site/_legal/terms': typeof SiteLegalTermsRoute
  '/_site/contributors/opengraph-image': typeof SiteContributorsOpengraphImageRoute
  '/_site/features/ai-crawler-logs': typeof SiteFeaturesAiCrawlerLogsRoute
  '/_site/features/conversations': typeof SiteFeaturesConversationsRoute
  '/_site/features/personas': typeof SiteFeaturesPersonasRoute
  '/_site/integrations/$id': typeof SiteIntegrationsIdRoute
  '/_site/integrations/github': typeof SiteIntegrationsGithubRoute
  '/_site/integrations/granola': typeof SiteIntegrationsGranolaRoute
  '/_site/integrations/linear': typeof SiteIntegrationsLinearRoute
  '/_site/integrations/slack': typeof SiteIntegrationsSlackRoute
  '/_site/notra-vs-{$slug}/opengraph-image': typeof SiteNotraVsChar123slugChar125OpengraphImageRoute
  '/_site/offering/report': typeof SiteOfferingReportRoute
  '/agent/auth/authorize': typeof AgentAuthAuthorizeRoute
  '/agent/auth/claim': typeof AgentAuthClaimRoute
  '/agent/auth/register': typeof AgentAuthRegisterRoute
  '/agent/auth/revoke': typeof AgentAuthRevokeRoute
  '/agent/auth/token': typeof AgentAuthTokenRoute
  '/api/c15t/$': typeof ApiC15tSplatRoute
  '/api/offering-check/preflight': typeof ApiOfferingCheckPreflightRoute
  '/api/star-video/render': typeof ApiStarVideoRenderRoute
  '/api/star-video/repo': typeof ApiStarVideoRepoRoute
  '/.well-known/mcp/': typeof DotwellKnownMcpIndexRoute
  '/_site/compare/': typeof SiteCompareIndexRoute
  '/_site/contributors/': typeof SiteContributorsIndexRoute
  '/_site/features/': typeof SiteFeaturesIndexRoute
  '/_site/integrations/': typeof SiteIntegrationsIndexRoute
  '/_site/mcp/': typeof SiteMcpIndexRoute
  '/_site/notra-vs-{$slug}/': typeof SiteNotraVsChar123slugChar125IndexRoute
  '/_site/offering/': typeof SiteOfferingIndexRoute
  '/_site/state-of-ai-search/': typeof SiteStateOfAiSearchIndexRoute
  '/api/offering-check/': typeof ApiOfferingCheckIndexRoute
  '/_site/features/marketing/assets': typeof SiteFeaturesMarketingAssetsRoute
  '/_site/mcp/use-cases/$slug': typeof SiteMcpUseCasesSlugRoute
  '/api/star-video/github/authorize': typeof ApiStarVideoGithubAuthorizeRoute
  '/api/star-video/github/callback': typeof ApiStarVideoGithubCallbackRoute
  '/_site/_blog/blog/': typeof SiteBlogBlogIndexRoute
  '/_site/_changelog/changelog/': typeof SiteChangelogChangelogIndexRoute
  '/_site/mcp/use-cases/': typeof SiteMcpUseCasesIndexRoute
  '/_site/state-of-ai-search/$category/': typeof SiteStateOfAiSearchCategoryIndexRoute
  '/_site/_blog/blog/$slug/opengraph-image': typeof SiteBlogBlogSlugOpengraphImageRoute
  '/_site/_changelog/changelog/$name/$slug': typeof SiteChangelogChangelogNameSlugRoute
  '/_site/_changelog/changelog/notra/$slug': typeof SiteChangelogChangelogNotraSlugRoute
  '/_site/state-of-ai-search/$category/$edition/data.csv': typeof SiteStateOfAiSearchCategoryEditionDataDotcsvRoute
  '/_site/state-of-ai-search/$category/$edition/opengraph-image': typeof SiteStateOfAiSearchCategoryEditionOpengraphImageRoute
  '/_site/_blog/blog/$slug/': typeof SiteBlogBlogSlugIndexRoute
  '/_site/_changelog/changelog/$name/': typeof SiteChangelogChangelogNameIndexRoute
  '/_site/_changelog/changelog/notra/': typeof SiteChangelogChangelogNotraIndexRoute
  '/_site/state-of-ai-search/$category/$edition/': typeof SiteStateOfAiSearchCategoryEditionIndexRoute
  '/_site/_blog/blog/author/$slug/opengraph-image': typeof SiteBlogBlogAuthorSlugOpengraphImageRoute
  '/_site/_blog/blog/author/$slug/': typeof SiteBlogBlogAuthorSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth.md'
    | '/feedback.md'
    | '/ip-checker.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/schema-map.xml'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/integrations.json'
    | '/.well-known/oauth-protected-resource'
    | '/home'
    | '/landing'
    | '/about'
    | '/agent'
    | '/brand'
    | '/contact'
    | '/feedback-md'
    | '/free-hat'
    | '/html-to-figma'
    | '/html-to-paper'
    | '/ip-checker'
    | '/oss-program'
    | '/pricing'
    | '/repo-star-video'
    | '/twitter-thread-creator'
    | '/api/contact'
    | '/api/ip-checker'
    | '/api/llms.txt'
    | '/api/oss-program'
    | '/api/status'
    | '/api/v1'
    | '/developers/llms.txt'
    | '/marketing/chat'
    | '/md/$'
    | '/schema/notra.jsonl'
    | '/v1/status'
    | '/api/'
    | '/v1/'
    | '/.well-known/mcp/server-card.json'
    | '/legal'
    | '/privacy'
    | '/terms'
    | '/contributors/opengraph-image'
    | '/features/ai-crawler-logs'
    | '/features/conversations'
    | '/features/personas'
    | '/integrations/$id'
    | '/integrations/github'
    | '/integrations/granola'
    | '/integrations/linear'
    | '/integrations/slack'
    | '/notra-vs-{$slug}/opengraph-image'
    | '/offering/report'
    | '/agent/auth/authorize'
    | '/agent/auth/claim'
    | '/agent/auth/register'
    | '/agent/auth/revoke'
    | '/agent/auth/token'
    | '/api/c15t/$'
    | '/api/offering-check/preflight'
    | '/api/star-video/render'
    | '/api/star-video/repo'
    | '/.well-known/mcp/'
    | '/compare/'
    | '/contributors/'
    | '/features/'
    | '/integrations/'
    | '/mcp/'
    | '/notra-vs-{$slug}/'
    | '/offering/'
    | '/state-of-ai-search/'
    | '/api/offering-check/'
    | '/features/marketing/assets'
    | '/mcp/use-cases/$slug'
    | '/api/star-video/github/authorize'
    | '/api/star-video/github/callback'
    | '/blog/'
    | '/changelog/'
    | '/mcp/use-cases/'
    | '/state-of-ai-search/$category/'
    | '/blog/$slug/opengraph-image'
    | '/changelog/$name/$slug'
    | '/changelog/notra/$slug'
    | '/state-of-ai-search/$category/$edition/data.csv'
    | '/state-of-ai-search/$category/$edition/opengraph-image'
    | '/blog/$slug/'
    | '/changelog/$name/'
    | '/changelog/notra/'
    | '/state-of-ai-search/$category/$edition/'
    | '/blog/author/$slug/opengraph-image'
    | '/blog/author/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth.md'
    | '/feedback.md'
    | '/ip-checker.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/schema-map.xml'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/integrations.json'
    | '/.well-known/oauth-protected-resource'
    | '/home'
    | '/landing'
    | '/about'
    | '/agent'
    | '/brand'
    | '/contact'
    | '/feedback-md'
    | '/free-hat'
    | '/html-to-figma'
    | '/html-to-paper'
    | '/ip-checker'
    | '/oss-program'
    | '/pricing'
    | '/repo-star-video'
    | '/twitter-thread-creator'
    | '/api/contact'
    | '/api/ip-checker'
    | '/api/llms.txt'
    | '/api/oss-program'
    | '/api/status'
    | '/api/v1'
    | '/developers/llms.txt'
    | '/marketing/chat'
    | '/md/$'
    | '/schema/notra.jsonl'
    | '/v1/status'
    | '/api'
    | '/v1'
    | '/.well-known/mcp/server-card.json'
    | '/legal'
    | '/privacy'
    | '/terms'
    | '/contributors/opengraph-image'
    | '/features/ai-crawler-logs'
    | '/features/conversations'
    | '/features/personas'
    | '/integrations/$id'
    | '/integrations/github'
    | '/integrations/granola'
    | '/integrations/linear'
    | '/integrations/slack'
    | '/notra-vs-{$slug}/opengraph-image'
    | '/offering/report'
    | '/agent/auth/authorize'
    | '/agent/auth/claim'
    | '/agent/auth/register'
    | '/agent/auth/revoke'
    | '/agent/auth/token'
    | '/api/c15t/$'
    | '/api/offering-check/preflight'
    | '/api/star-video/render'
    | '/api/star-video/repo'
    | '/.well-known/mcp'
    | '/compare'
    | '/contributors'
    | '/features'
    | '/integrations'
    | '/mcp'
    | '/notra-vs-{$slug}'
    | '/offering'
    | '/state-of-ai-search'
    | '/api/offering-check'
    | '/features/marketing/assets'
    | '/mcp/use-cases/$slug'
    | '/api/star-video/github/authorize'
    | '/api/star-video/github/callback'
    | '/blog'
    | '/changelog'
    | '/mcp/use-cases'
    | '/state-of-ai-search/$category'
    | '/blog/$slug/opengraph-image'
    | '/changelog/$name/$slug'
    | '/changelog/notra/$slug'
    | '/state-of-ai-search/$category/$edition/data.csv'
    | '/state-of-ai-search/$category/$edition/opengraph-image'
    | '/blog/$slug'
    | '/changelog/$name'
    | '/changelog/notra'
    | '/state-of-ai-search/$category/$edition'
    | '/blog/author/$slug/opengraph-image'
    | '/blog/author/$slug'
  id:
    | '__root__'
    | '/_landing'
    | '/_site'
    | '/ask'
    | '/auth.md'
    | '/feedback.md'
    | '/ip-checker.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/manifest.json'
    | '/robots.txt'
    | '/rss.xml'
    | '/schema-map.xml'
    | '/sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/integrations.json'
    | '/.well-known/oauth-protected-resource'
    | '/_landing/home'
    | '/_landing/landing'
    | '/_site/_blog'
    | '/_site/_changelog'
    | '/_site/_legal'
    | '/_site/about'
    | '/_site/agent'
    | '/_site/brand'
    | '/_site/contact'
    | '/_site/feedback-md'
    | '/_site/free-hat'
    | '/_site/html-to-figma'
    | '/_site/html-to-paper'
    | '/_site/ip-checker'
    | '/_site/oss-program'
    | '/_site/pricing'
    | '/_site/repo-star-video'
    | '/_site/twitter-thread-creator'
    | '/api/contact'
    | '/api/ip-checker'
    | '/api/llms.txt'
    | '/api/oss-program'
    | '/api/status'
    | '/api/v1'
    | '/developers/llms.txt'
    | '/marketing/chat'
    | '/md/$'
    | '/schema/notra.jsonl'
    | '/v1/status'
    | '/_landing/'
    | '/api/'
    | '/v1/'
    | '/.well-known/mcp/server-card.json'
    | '/_site/_legal/legal'
    | '/_site/_legal/privacy'
    | '/_site/_legal/terms'
    | '/_site/contributors/opengraph-image'
    | '/_site/features/ai-crawler-logs'
    | '/_site/features/conversations'
    | '/_site/features/personas'
    | '/_site/integrations/$id'
    | '/_site/integrations/github'
    | '/_site/integrations/granola'
    | '/_site/integrations/linear'
    | '/_site/integrations/slack'
    | '/_site/notra-vs-{$slug}/opengraph-image'
    | '/_site/offering/report'
    | '/agent/auth/authorize'
    | '/agent/auth/claim'
    | '/agent/auth/register'
    | '/agent/auth/revoke'
    | '/agent/auth/token'
    | '/api/c15t/$'
    | '/api/offering-check/preflight'
    | '/api/star-video/render'
    | '/api/star-video/repo'
    | '/.well-known/mcp/'
    | '/_site/compare/'
    | '/_site/contributors/'
    | '/_site/features/'
    | '/_site/integrations/'
    | '/_site/mcp/'
    | '/_site/notra-vs-{$slug}/'
    | '/_site/offering/'
    | '/_site/state-of-ai-search/'
    | '/api/offering-check/'
    | '/_site/features/marketing/assets'
    | '/_site/mcp/use-cases/$slug'
    | '/api/star-video/github/authorize'
    | '/api/star-video/github/callback'
    | '/_site/_blog/blog/'
    | '/_site/_changelog/changelog/'
    | '/_site/mcp/use-cases/'
    | '/_site/state-of-ai-search/$category/'
    | '/_site/_blog/blog/$slug/opengraph-image'
    | '/_site/_changelog/changelog/$name/$slug'
    | '/_site/_changelog/changelog/notra/$slug'
    | '/_site/state-of-ai-search/$category/$edition/data.csv'
    | '/_site/state-of-ai-search/$category/$edition/opengraph-image'
    | '/_site/_blog/blog/$slug/'
    | '/_site/_changelog/changelog/$name/'
    | '/_site/_changelog/changelog/notra/'
    | '/_site/state-of-ai-search/$category/$edition/'
    | '/_site/_blog/blog/author/$slug/opengraph-image'
    | '/_site/_blog/blog/author/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AskRoute: typeof AskRoute
  AuthDotmdRoute: typeof AuthDotmdRoute
  FeedbackDotmdRoute: typeof FeedbackDotmdRoute
  IpCheckerDotmdRoute: typeof IpCheckerDotmdRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SchemaMapDotxmlRoute: typeof SchemaMapDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownHttpMessageSignaturesDirectoryRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  DotwellKnownIntegrationsDotjsonRoute: typeof DotwellKnownIntegrationsDotjsonRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiIpCheckerRoute: typeof ApiIpCheckerRoute
  ApiLlmsDottxtRoute: typeof ApiLlmsDottxtRoute
  ApiOssProgramRoute: typeof ApiOssProgramRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiV1Route: typeof ApiV1Route
  DevelopersLlmsDottxtRoute: typeof DevelopersLlmsDottxtRoute
  MarketingChatRoute: typeof MarketingChatRoute
  MdSplatRoute: typeof MdSplatRoute
  SchemaNotraDotjsonlRoute: typeof SchemaNotraDotjsonlRoute
  V1StatusRoute: typeof V1StatusRoute
  ApiIndexRoute: typeof ApiIndexRoute
  V1IndexRoute: typeof V1IndexRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  AgentAuthAuthorizeRoute: typeof AgentAuthAuthorizeRoute
  AgentAuthClaimRoute: typeof AgentAuthClaimRoute
  AgentAuthRegisterRoute: typeof AgentAuthRegisterRoute
  AgentAuthRevokeRoute: typeof AgentAuthRevokeRoute
  AgentAuthTokenRoute: typeof AgentAuthTokenRoute
  ApiC15tSplatRoute: typeof ApiC15tSplatRoute
  ApiOfferingCheckPreflightRoute: typeof ApiOfferingCheckPreflightRoute
  ApiStarVideoRenderRoute: typeof ApiStarVideoRenderRoute
  ApiStarVideoRepoRoute: typeof ApiStarVideoRepoRoute
  DotwellKnownMcpIndexRoute: typeof DotwellKnownMcpIndexRoute
  ApiOfferingCheckIndexRoute: typeof ApiOfferingCheckIndexRoute
  ApiStarVideoGithubAuthorizeRoute: typeof ApiStarVideoGithubAuthorizeRoute
  ApiStarVideoGithubCallbackRoute: typeof ApiStarVideoGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback.md': {
      id: '/feedback.md'
      path: '/feedback.md'
      fullPath: '/feedback.md'
      preLoaderRoute: typeof FeedbackDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-checker.md': {
      id: '/ip-checker.md'
      path: '/ip-checker.md'
      fullPath: '/ip-checker.md'
      preLoaderRoute: typeof IpCheckerDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema-map.xml': {
      id: '/schema-map.xml'
      path: '/schema-map.xml'
      fullPath: '/schema-map.xml'
      preLoaderRoute: typeof SchemaMapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/http-message-signatures-directory': {
      id: '/.well-known/http-message-signatures-directory'
      path: '/.well-known/http-message-signatures-directory'
      fullPath: '/.well-known/http-message-signatures-directory'
      preLoaderRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/integrations.json': {
      id: '/.well-known/integrations.json'
      path: '/.well-known/integrations.json'
      fullPath: '/.well-known/integrations.json'
      preLoaderRoute: typeof DotwellKnownIntegrationsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/home': {
      id: '/_landing/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LandingHomeRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/landing': {
      id: '/_landing/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingLandingRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_site/_blog': {
      id: '/_site/_blog'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/_changelog': {
      id: '/_site/_changelog'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteChangelogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/_legal': {
      id: '/_site/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteLegalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/agent': {
      id: '/_site/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof SiteAgentRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/brand': {
      id: '/_site/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof SiteBrandRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/feedback-md': {
      id: '/_site/feedback-md'
      path: '/feedback-md'
      fullPath: '/feedback-md'
      preLoaderRoute: typeof SiteFeedbackMdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/free-hat': {
      id: '/_site/free-hat'
      path: '/free-hat'
      fullPath: '/free-hat'
      preLoaderRoute: typeof SiteFreeHatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/html-to-figma': {
      id: '/_site/html-to-figma'
      path: '/html-to-figma'
      fullPath: '/html-to-figma'
      preLoaderRoute: typeof SiteHtmlToFigmaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/html-to-paper': {
      id: '/_site/html-to-paper'
      path: '/html-to-paper'
      fullPath: '/html-to-paper'
      preLoaderRoute: typeof SiteHtmlToPaperRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ip-checker': {
      id: '/_site/ip-checker'
      path: '/ip-checker'
      fullPath: '/ip-checker'
      preLoaderRoute: typeof SiteIpCheckerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/oss-program': {
      id: '/_site/oss-program'
      path: '/oss-program'
      fullPath: '/oss-program'
      preLoaderRoute: typeof SiteOssProgramRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/repo-star-video': {
      id: '/_site/repo-star-video'
      path: '/repo-star-video'
      fullPath: '/repo-star-video'
      preLoaderRoute: typeof SiteRepoStarVideoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/twitter-thread-creator': {
      id: '/_site/twitter-thread-creator'
      path: '/twitter-thread-creator'
      fullPath: '/twitter-thread-creator'
      preLoaderRoute: typeof SiteTwitterThreadCreatorRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ip-checker': {
      id: '/api/ip-checker'
      path: '/api/ip-checker'
      fullPath: '/api/ip-checker'
      preLoaderRoute: typeof ApiIpCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms.txt': {
      id: '/api/llms.txt'
      path: '/api/llms.txt'
      fullPath: '/api/llms.txt'
      preLoaderRoute: typeof ApiLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oss-program': {
      id: '/api/oss-program'
      path: '/api/oss-program'
      fullPath: '/api/oss-program'
      preLoaderRoute: typeof ApiOssProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/llms.txt': {
      id: '/developers/llms.txt'
      path: '/developers/llms.txt'
      fullPath: '/developers/llms.txt'
      preLoaderRoute: typeof DevelopersLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/chat': {
      id: '/marketing/chat'
      path: '/marketing/chat'
      fullPath: '/marketing/chat'
      preLoaderRoute: typeof MarketingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md/$': {
      id: '/md/$'
      path: '/md/$'
      fullPath: '/md/$'
      preLoaderRoute: typeof MdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema/notra.jsonl': {
      id: '/schema/notra.jsonl'
      path: '/schema/notra.jsonl'
      fullPath: '/schema/notra.jsonl'
      preLoaderRoute: typeof SchemaNotraDotjsonlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/': {
      id: '/v1/'
      path: '/v1'
      fullPath: '/v1/'
      preLoaderRoute: typeof V1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/status': {
      id: '/v1/status'
      path: '/v1/status'
      fullPath: '/v1/status'
      preLoaderRoute: typeof V1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/': {
      id: '/.well-known/mcp/'
      path: '/.well-known/mcp'
      fullPath: '/.well-known/mcp/'
      preLoaderRoute: typeof DotwellKnownMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/_legal/legal': {
      id: '/_site/_legal/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof SiteLegalLegalRouteImport
      parentRoute: typeof SiteLegalRoute
    }
    '/_site/_legal/privacy': {
      id: '/_site/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SiteLegalPrivacyRouteImport
      parentRoute: typeof SiteLegalRoute
    }
    '/_site/_legal/terms': {
      id: '/_site/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteLegalTermsRouteImport
      parentRoute: typeof SiteLegalRoute
    }
    '/_site/compare/': {
      id: '/_site/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof SiteCompareIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contributors/': {
      id: '/_site/contributors/'
      path: '/contributors'
      fullPath: '/contributors/'
      preLoaderRoute: typeof SiteContributorsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contributors/opengraph-image': {
      id: '/_site/contributors/opengraph-image'
      path: '/contributors/opengraph-image'
      fullPath: '/contributors/opengraph-image'
      preLoaderRoute: typeof SiteContributorsOpengraphImageRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features/': {
      id: '/_site/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof SiteFeaturesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features/ai-crawler-logs': {
      id: '/_site/features/ai-crawler-logs'
      path: '/features/ai-crawler-logs'
      fullPath: '/features/ai-crawler-logs'
      preLoaderRoute: typeof SiteFeaturesAiCrawlerLogsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features/conversations': {
      id: '/_site/features/conversations'
      path: '/features/conversations'
      fullPath: '/features/conversations'
      preLoaderRoute: typeof SiteFeaturesConversationsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features/personas': {
      id: '/_site/features/personas'
      path: '/features/personas'
      fullPath: '/features/personas'
      preLoaderRoute: typeof SiteFeaturesPersonasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/': {
      id: '/_site/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof SiteIntegrationsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/$id': {
      id: '/_site/integrations/$id'
      path: '/integrations/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof SiteIntegrationsIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/github': {
      id: '/_site/integrations/github'
      path: '/integrations/github'
      fullPath: '/integrations/github'
      preLoaderRoute: typeof SiteIntegrationsGithubRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/granola': {
      id: '/_site/integrations/granola'
      path: '/integrations/granola'
      fullPath: '/integrations/granola'
      preLoaderRoute: typeof SiteIntegrationsGranolaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/linear': {
      id: '/_site/integrations/linear'
      path: '/integrations/linear'
      fullPath: '/integrations/linear'
      preLoaderRoute: typeof SiteIntegrationsLinearRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations/slack': {
      id: '/_site/integrations/slack'
      path: '/integrations/slack'
      fullPath: '/integrations/slack'
      preLoaderRoute: typeof SiteIntegrationsSlackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mcp/': {
      id: '/_site/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof SiteMcpIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/notra-vs-{$slug}/': {
      id: '/_site/notra-vs-{$slug}/'
      path: '/notra-vs-{$slug}'
      fullPath: '/notra-vs-{$slug}/'
      preLoaderRoute: typeof SiteNotraVsChar123slugChar125IndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/notra-vs-{$slug}/opengraph-image': {
      id: '/_site/notra-vs-{$slug}/opengraph-image'
      path: '/notra-vs-{$slug}/opengraph-image'
      fullPath: '/notra-vs-{$slug}/opengraph-image'
      preLoaderRoute: typeof SiteNotraVsChar123slugChar125OpengraphImageRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/offering/': {
      id: '/_site/offering/'
      path: '/offering'
      fullPath: '/offering/'
      preLoaderRoute: typeof SiteOfferingIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/offering/report': {
      id: '/_site/offering/report'
      path: '/offering/report'
      fullPath: '/offering/report'
      preLoaderRoute: typeof SiteOfferingReportRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/state-of-ai-search/': {
      id: '/_site/state-of-ai-search/'
      path: '/state-of-ai-search'
      fullPath: '/state-of-ai-search/'
      preLoaderRoute: typeof SiteStateOfAiSearchIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/agent/auth/authorize': {
      id: '/agent/auth/authorize'
      path: '/agent/auth/authorize'
      fullPath: '/agent/auth/authorize'
      preLoaderRoute: typeof AgentAuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/auth/claim': {
      id: '/agent/auth/claim'
      path: '/agent/auth/claim'
      fullPath: '/agent/auth/claim'
      preLoaderRoute: typeof AgentAuthClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/auth/register': {
      id: '/agent/auth/register'
      path: '/agent/auth/register'
      fullPath: '/agent/auth/register'
      preLoaderRoute: typeof AgentAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/auth/revoke': {
      id: '/agent/auth/revoke'
      path: '/agent/auth/revoke'
      fullPath: '/agent/auth/revoke'
      preLoaderRoute: typeof AgentAuthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/auth/token': {
      id: '/agent/auth/token'
      path: '/agent/auth/token'
      fullPath: '/agent/auth/token'
      preLoaderRoute: typeof AgentAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/c15t/$': {
      id: '/api/c15t/$'
      path: '/api/c15t/$'
      fullPath: '/api/c15t/$'
      preLoaderRoute: typeof ApiC15tSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offering-check/': {
      id: '/api/offering-check/'
      path: '/api/offering-check'
      fullPath: '/api/offering-check/'
      preLoaderRoute: typeof ApiOfferingCheckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offering-check/preflight': {
      id: '/api/offering-check/preflight'
      path: '/api/offering-check/preflight'
      fullPath: '/api/offering-check/preflight'
      preLoaderRoute: typeof ApiOfferingCheckPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/star-video/render': {
      id: '/api/star-video/render'
      path: '/api/star-video/render'
      fullPath: '/api/star-video/render'
      preLoaderRoute: typeof ApiStarVideoRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/star-video/repo': {
      id: '/api/star-video/repo'
      path: '/api/star-video/repo'
      fullPath: '/api/star-video/repo'
      preLoaderRoute: typeof ApiStarVideoRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/_blog/blog/': {
      id: '/_site/_blog/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogBlogIndexRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/_changelog/changelog/': {
      id: '/_site/_changelog/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof SiteChangelogChangelogIndexRouteImport
      parentRoute: typeof SiteChangelogRoute
    }
    '/_site/features/marketing/assets': {
      id: '/_site/features/marketing/assets'
      path: '/features/marketing/assets'
      fullPath: '/features/marketing/assets'
      preLoaderRoute: typeof SiteFeaturesMarketingAssetsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mcp/use-cases/': {
      id: '/_site/mcp/use-cases/'
      path: '/mcp/use-cases'
      fullPath: '/mcp/use-cases/'
      preLoaderRoute: typeof SiteMcpUseCasesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mcp/use-cases/$slug': {
      id: '/_site/mcp/use-cases/$slug'
      path: '/mcp/use-cases/$slug'
      fullPath: '/mcp/use-cases/$slug'
      preLoaderRoute: typeof SiteMcpUseCasesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/state-of-ai-search/$category/': {
      id: '/_site/state-of-ai-search/$category/'
      path: '/state-of-ai-search/$category'
      fullPath: '/state-of-ai-search/$category/'
      preLoaderRoute: typeof SiteStateOfAiSearchCategoryIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/star-video/github/authorize': {
      id: '/api/star-video/github/authorize'
      path: '/api/star-video/github/authorize'
      fullPath: '/api/star-video/github/authorize'
      preLoaderRoute: typeof ApiStarVideoGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/star-video/github/callback': {
      id: '/api/star-video/github/callback'
      path: '/api/star-video/github/callback'
      fullPath: '/api/star-video/github/callback'
      preLoaderRoute: typeof ApiStarVideoGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/_blog/blog/$slug/': {
      id: '/_site/_blog/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof SiteBlogBlogSlugIndexRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/_blog/blog/$slug/opengraph-image': {
      id: '/_site/_blog/blog/$slug/opengraph-image'
      path: '/blog/$slug/opengraph-image'
      fullPath: '/blog/$slug/opengraph-image'
      preLoaderRoute: typeof SiteBlogBlogSlugOpengraphImageRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/_changelog/changelog/$name/': {
      id: '/_site/_changelog/changelog/$name/'
      path: '/changelog/$name'
      fullPath: '/changelog/$name/'
      preLoaderRoute: typeof SiteChangelogChangelogNameIndexRouteImport
      parentRoute: typeof SiteChangelogRoute
    }
    '/_site/_changelog/changelog/$name/$slug': {
      id: '/_site/_changelog/changelog/$name/$slug'
      path: '/changelog/$name/$slug'
      fullPath: '/changelog/$name/$slug'
      preLoaderRoute: typeof SiteChangelogChangelogNameSlugRouteImport
      parentRoute: typeof SiteChangelogRoute
    }
    '/_site/_changelog/changelog/notra/': {
      id: '/_site/_changelog/changelog/notra/'
      path: '/changelog/notra'
      fullPath: '/changelog/notra/'
      preLoaderRoute: typeof SiteChangelogChangelogNotraIndexRouteImport
      parentRoute: typeof SiteChangelogRoute
    }
    '/_site/_changelog/changelog/notra/$slug': {
      id: '/_site/_changelog/changelog/notra/$slug'
      path: '/changelog/notra/$slug'
      fullPath: '/changelog/notra/$slug'
      preLoaderRoute: typeof SiteChangelogChangelogNotraSlugRouteImport
      parentRoute: typeof SiteChangelogRoute
    }
    '/_site/state-of-ai-search/$category/$edition/': {
      id: '/_site/state-of-ai-search/$category/$edition/'
      path: '/state-of-ai-search/$category/$edition'
      fullPath: '/state-of-ai-search/$category/$edition/'
      preLoaderRoute: typeof SiteStateOfAiSearchCategoryEditionIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/state-of-ai-search/$category/$edition/data.csv': {
      id: '/_site/state-of-ai-search/$category/$edition/data.csv'
      path: '/state-of-ai-search/$category/$edition/data.csv'
      fullPath: '/state-of-ai-search/$category/$edition/data.csv'
      preLoaderRoute: typeof SiteStateOfAiSearchCategoryEditionDataDotcsvRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/state-of-ai-search/$category/$edition/opengraph-image': {
      id: '/_site/state-of-ai-search/$category/$edition/opengraph-image'
      path: '/state-of-ai-search/$category/$edition/opengraph-image'
      fullPath: '/state-of-ai-search/$category/$edition/opengraph-image'
      preLoaderRoute: typeof SiteStateOfAiSearchCategoryEditionOpengraphImageRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/_blog/blog/author/$slug/': {
      id: '/_site/_blog/blog/author/$slug/'
      path: '/blog/author/$slug'
      fullPath: '/blog/author/$slug/'
      preLoaderRoute: typeof SiteBlogBlogAuthorSlugIndexRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/_blog/blog/author/$slug/opengraph-image': {
      id: '/_site/_blog/blog/author/$slug/opengraph-image'
      path: '/blog/author/$slug/opengraph-image'
      fullPath: '/blog/author/$slug/opengraph-image'
      preLoaderRoute: typeof SiteBlogBlogAuthorSlugOpengraphImageRouteImport
      parentRoute: typeof SiteBlogRoute
    }
  }
}

interface LandingRouteChildren {
  LandingHomeRoute: typeof LandingHomeRoute
  LandingLandingRoute: typeof LandingLandingRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingHomeRoute: LandingHomeRoute,
  LandingLandingRoute: LandingLandingRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface SiteBlogRouteChildren {
  SiteBlogBlogIndexRoute: typeof SiteBlogBlogIndexRoute
  SiteBlogBlogSlugOpengraphImageRoute: typeof SiteBlogBlogSlugOpengraphImageRoute
  SiteBlogBlogSlugIndexRoute: typeof SiteBlogBlogSlugIndexRoute
  SiteBlogBlogAuthorSlugOpengraphImageRoute: typeof SiteBlogBlogAuthorSlugOpengraphImageRoute
  SiteBlogBlogAuthorSlugIndexRoute: typeof SiteBlogBlogAuthorSlugIndexRoute
}

const SiteBlogRouteChildren: SiteBlogRouteChildren = {
  SiteBlogBlogIndexRoute: SiteBlogBlogIndexRoute,
  SiteBlogBlogSlugOpengraphImageRoute: SiteBlogBlogSlugOpengraphImageRoute,
  SiteBlogBlogSlugIndexRoute: SiteBlogBlogSlugIndexRoute,
  SiteBlogBlogAuthorSlugOpengraphImageRoute:
    SiteBlogBlogAuthorSlugOpengraphImageRoute,
  SiteBlogBlogAuthorSlugIndexRoute: SiteBlogBlogAuthorSlugIndexRoute,
}

const SiteBlogRouteWithChildren = SiteBlogRoute._addFileChildren(
  SiteBlogRouteChildren,
)

interface SiteChangelogRouteChildren {
  SiteChangelogChangelogIndexRoute: typeof SiteChangelogChangelogIndexRoute
  SiteChangelogChangelogNameSlugRoute: typeof SiteChangelogChangelogNameSlugRoute
  SiteChangelogChangelogNotraSlugRoute: typeof SiteChangelogChangelogNotraSlugRoute
  SiteChangelogChangelogNameIndexRoute: typeof SiteChangelogChangelogNameIndexRoute
  SiteChangelogChangelogNotraIndexRoute: typeof SiteChangelogChangelogNotraIndexRoute
}

const SiteChangelogRouteChildren: SiteChangelogRouteChildren = {
  SiteChangelogChangelogIndexRoute: SiteChangelogChangelogIndexRoute,
  SiteChangelogChangelogNameSlugRoute: SiteChangelogChangelogNameSlugRoute,
  SiteChangelogChangelogNotraSlugRoute: SiteChangelogChangelogNotraSlugRoute,
  SiteChangelogChangelogNameIndexRoute: SiteChangelogChangelogNameIndexRoute,
  SiteChangelogChangelogNotraIndexRoute: SiteChangelogChangelogNotraIndexRoute,
}

const SiteChangelogRouteWithChildren = SiteChangelogRoute._addFileChildren(
  SiteChangelogRouteChildren,
)

interface SiteLegalRouteChildren {
  SiteLegalLegalRoute: typeof SiteLegalLegalRoute
  SiteLegalPrivacyRoute: typeof SiteLegalPrivacyRoute
  SiteLegalTermsRoute: typeof SiteLegalTermsRoute
}

const SiteLegalRouteChildren: SiteLegalRouteChildren = {
  SiteLegalLegalRoute: SiteLegalLegalRoute,
  SiteLegalPrivacyRoute: SiteLegalPrivacyRoute,
  SiteLegalTermsRoute: SiteLegalTermsRoute,
}

const SiteLegalRouteWithChildren = SiteLegalRoute._addFileChildren(
  SiteLegalRouteChildren,
)

interface SiteRouteChildren {
  SiteBlogRoute: typeof SiteBlogRouteWithChildren
  SiteChangelogRoute: typeof SiteChangelogRouteWithChildren
  SiteLegalRoute: typeof SiteLegalRouteWithChildren
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAgentRoute: typeof SiteAgentRoute
  SiteBrandRoute: typeof SiteBrandRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFeedbackMdRoute: typeof SiteFeedbackMdRoute
  SiteFreeHatRoute: typeof SiteFreeHatRoute
  SiteHtmlToFigmaRoute: typeof SiteHtmlToFigmaRoute
  SiteHtmlToPaperRoute: typeof SiteHtmlToPaperRoute
  SiteIpCheckerRoute: typeof SiteIpCheckerRoute
  SiteOssProgramRoute: typeof SiteOssProgramRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteRepoStarVideoRoute: typeof SiteRepoStarVideoRoute
  SiteTwitterThreadCreatorRoute: typeof SiteTwitterThreadCreatorRoute
  SiteContributorsOpengraphImageRoute: typeof SiteContributorsOpengraphImageRoute
  SiteFeaturesAiCrawlerLogsRoute: typeof SiteFeaturesAiCrawlerLogsRoute
  SiteFeaturesConversationsRoute: typeof SiteFeaturesConversationsRoute
  SiteFeaturesPersonasRoute: typeof SiteFeaturesPersonasRoute
  SiteIntegrationsIdRoute: typeof SiteIntegrationsIdRoute
  SiteIntegrationsGithubRoute: typeof SiteIntegrationsGithubRoute
  SiteIntegrationsGranolaRoute: typeof SiteIntegrationsGranolaRoute
  SiteIntegrationsLinearRoute: typeof SiteIntegrationsLinearRoute
  SiteIntegrationsSlackRoute: typeof SiteIntegrationsSlackRoute
  SiteNotraVsChar123slugChar125OpengraphImageRoute: typeof SiteNotraVsChar123slugChar125OpengraphImageRoute
  SiteOfferingReportRoute: typeof SiteOfferingReportRoute
  SiteCompareIndexRoute: typeof SiteCompareIndexRoute
  SiteContributorsIndexRoute: typeof SiteContributorsIndexRoute
  SiteFeaturesIndexRoute: typeof SiteFeaturesIndexRoute
  SiteIntegrationsIndexRoute: typeof SiteIntegrationsIndexRoute
  SiteMcpIndexRoute: typeof SiteMcpIndexRoute
  SiteNotraVsChar123slugChar125IndexRoute: typeof SiteNotraVsChar123slugChar125IndexRoute
  SiteOfferingIndexRoute: typeof SiteOfferingIndexRoute
  SiteStateOfAiSearchIndexRoute: typeof SiteStateOfAiSearchIndexRoute
  SiteFeaturesMarketingAssetsRoute: typeof SiteFeaturesMarketingAssetsRoute
  SiteMcpUseCasesSlugRoute: typeof SiteMcpUseCasesSlugRoute
  SiteMcpUseCasesIndexRoute: typeof SiteMcpUseCasesIndexRoute
  SiteStateOfAiSearchCategoryIndexRoute: typeof SiteStateOfAiSearchCategoryIndexRoute
  SiteStateOfAiSearchCategoryEditionDataDotcsvRoute: typeof SiteStateOfAiSearchCategoryEditionDataDotcsvRoute
  SiteStateOfAiSearchCategoryEditionOpengraphImageRoute: typeof SiteStateOfAiSearchCategoryEditionOpengraphImageRoute
  SiteStateOfAiSearchCategoryEditionIndexRoute: typeof SiteStateOfAiSearchCategoryEditionIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBlogRoute: SiteBlogRouteWithChildren,
  SiteChangelogRoute: SiteChangelogRouteWithChildren,
  SiteLegalRoute: SiteLegalRouteWithChildren,
  SiteAboutRoute: SiteAboutRoute,
  SiteAgentRoute: SiteAgentRoute,
  SiteBrandRoute: SiteBrandRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFeedbackMdRoute: SiteFeedbackMdRoute,
  SiteFreeHatRoute: SiteFreeHatRoute,
  SiteHtmlToFigmaRoute: SiteHtmlToFigmaRoute,
  SiteHtmlToPaperRoute: SiteHtmlToPaperRoute,
  SiteIpCheckerRoute: SiteIpCheckerRoute,
  SiteOssProgramRoute: SiteOssProgramRoute,
  SitePricingRoute: SitePricingRoute,
  SiteRepoStarVideoRoute: SiteRepoStarVideoRoute,
  SiteTwitterThreadCreatorRoute: SiteTwitterThreadCreatorRoute,
  SiteContributorsOpengraphImageRoute: SiteContributorsOpengraphImageRoute,
  SiteFeaturesAiCrawlerLogsRoute: SiteFeaturesAiCrawlerLogsRoute,
  SiteFeaturesConversationsRoute: SiteFeaturesConversationsRoute,
  SiteFeaturesPersonasRoute: SiteFeaturesPersonasRoute,
  SiteIntegrationsIdRoute: SiteIntegrationsIdRoute,
  SiteIntegrationsGithubRoute: SiteIntegrationsGithubRoute,
  SiteIntegrationsGranolaRoute: SiteIntegrationsGranolaRoute,
  SiteIntegrationsLinearRoute: SiteIntegrationsLinearRoute,
  SiteIntegrationsSlackRoute: SiteIntegrationsSlackRoute,
  SiteNotraVsChar123slugChar125OpengraphImageRoute:
    SiteNotraVsChar123slugChar125OpengraphImageRoute,
  SiteOfferingReportRoute: SiteOfferingReportRoute,
  SiteCompareIndexRoute: SiteCompareIndexRoute,
  SiteContributorsIndexRoute: SiteContributorsIndexRoute,
  SiteFeaturesIndexRoute: SiteFeaturesIndexRoute,
  SiteIntegrationsIndexRoute: SiteIntegrationsIndexRoute,
  SiteMcpIndexRoute: SiteMcpIndexRoute,
  SiteNotraVsChar123slugChar125IndexRoute:
    SiteNotraVsChar123slugChar125IndexRoute,
  SiteOfferingIndexRoute: SiteOfferingIndexRoute,
  SiteStateOfAiSearchIndexRoute: SiteStateOfAiSearchIndexRoute,
  SiteFeaturesMarketingAssetsRoute: SiteFeaturesMarketingAssetsRoute,
  SiteMcpUseCasesSlugRoute: SiteMcpUseCasesSlugRoute,
  SiteMcpUseCasesIndexRoute: SiteMcpUseCasesIndexRoute,
  SiteStateOfAiSearchCategoryIndexRoute: SiteStateOfAiSearchCategoryIndexRoute,
  SiteStateOfAiSearchCategoryEditionDataDotcsvRoute:
    SiteStateOfAiSearchCategoryEditionDataDotcsvRoute,
  SiteStateOfAiSearchCategoryEditionOpengraphImageRoute:
    SiteStateOfAiSearchCategoryEditionOpengraphImageRoute,
  SiteStateOfAiSearchCategoryEditionIndexRoute:
    SiteStateOfAiSearchCategoryEditionIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AskRoute: AskRoute,
  AuthDotmdRoute: AuthDotmdRoute,
  FeedbackDotmdRoute: FeedbackDotmdRoute,
  IpCheckerDotmdRoute: IpCheckerDotmdRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SchemaMapDotxmlRoute: SchemaMapDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownHttpMessageSignaturesDirectoryRoute:
    DotwellKnownHttpMessageSignaturesDirectoryRoute,
  DotwellKnownIntegrationsDotjsonRoute: DotwellKnownIntegrationsDotjsonRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiContactRoute: ApiContactRoute,
  ApiIpCheckerRoute: ApiIpCheckerRoute,
  ApiLlmsDottxtRoute: ApiLlmsDottxtRoute,
  ApiOssProgramRoute: ApiOssProgramRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiV1Route: ApiV1Route,
  DevelopersLlmsDottxtRoute: DevelopersLlmsDottxtRoute,
  MarketingChatRoute: MarketingChatRoute,
  MdSplatRoute: MdSplatRoute,
  SchemaNotraDotjsonlRoute: SchemaNotraDotjsonlRoute,
  V1StatusRoute: V1StatusRoute,
  ApiIndexRoute: ApiIndexRoute,
  V1IndexRoute: V1IndexRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  AgentAuthAuthorizeRoute: AgentAuthAuthorizeRoute,
  AgentAuthClaimRoute: AgentAuthClaimRoute,
  AgentAuthRegisterRoute: AgentAuthRegisterRoute,
  AgentAuthRevokeRoute: AgentAuthRevokeRoute,
  AgentAuthTokenRoute: AgentAuthTokenRoute,
  ApiC15tSplatRoute: ApiC15tSplatRoute,
  ApiOfferingCheckPreflightRoute: ApiOfferingCheckPreflightRoute,
  ApiStarVideoRenderRoute: ApiStarVideoRenderRoute,
  ApiStarVideoRepoRoute: ApiStarVideoRepoRoute,
  DotwellKnownMcpIndexRoute: DotwellKnownMcpIndexRoute,
  ApiOfferingCheckIndexRoute: ApiOfferingCheckIndexRoute,
  ApiStarVideoGithubAuthorizeRoute: ApiStarVideoGithubAuthorizeRoute,
  ApiStarVideoGithubCallbackRoute: ApiStarVideoGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
