import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { ShowcaseEntryPageProps } from "~types/showcase";

import { changelog } from "@/../.source/server";
import { getMDXComponents } from "@/../mdx-components";
import { NotraMark } from "@/components/notra-mark";
import { TableOfContents } from "@/components/table-of-contents";
import { formatChangelogDate } from "@/utils/changelog";
import {
  buildArticleJsonLd,
  buildBreadcrumbJsonLd,
  serializeJsonLd,
} from "@/utils/jsonld";
import {
  DEFAULT_SOCIAL_IMAGE,
  TWITTER_HANDLE,
  pageAlternates,
} from "@/utils/metadata";
import {
  getShowcaseCompany,
  getShowcaseEntrySlug,
  SHOWCASE_COMPANIES,
} from "@/utils/showcase";
import { SITE_URL } from "@/utils/urls";

export function generateStaticParams() {
  return SHOWCASE_COMPANIES.flatMap((company) =>
    changelog.flatMap((entry) =>
      entry.info.path.startsWith(`${company.slug}/`)
        ? [
            {
              name: company.slug,
              slug: getShowcaseEntrySlug(entry.info.path),
            },
          ]
        : []
    )
  );
}

export async function generateMetadata({
  params,
}: ShowcaseEntryPageProps): Promise<Metadata> {
  const { name, slug } = await params;
  const entry = changelog.find(
    (item) => item.info.path === `${name}/${slug}.mdx`
  );

  if (!entry) {
    return {};
  }

  const url = `${SITE_URL}/changelog/${name}/${slug}`;

  return {
    title: { absolute: entry.title },
    description: entry.description,
    alternates: pageAlternates(url),
    openGraph: {
      title: entry.title,
      description: entry.description,
      url,
      type: "article",
      publishedTime: entry.date,
      modifiedTime: entry.date,
      siteName: "Notra",
      images: [DEFAULT_SOCIAL_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: entry.title,
      description: entry.description,
      images: [DEFAULT_SOCIAL_IMAGE.url],
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
    },
  };
}

export default async function ShowcaseEntryPage({
  params,
}: ShowcaseEntryPageProps) {
  const { name, slug } = await params;
  const company = getShowcaseCompany(name);
  const entry = changelog.find(
    (item) => item.info.path === `${name}/${slug}.mdx`
  );

  if (!company || !entry) {
    notFound();
  }

  const MDX = entry.body;
  const url = `${SITE_URL}/changelog/${name}/${slug}`;
  const articleJsonLd = buildArticleJsonLd({
    url,
    title: entry.title,
    description: entry.description,
    imageUrl: `${SITE_URL}${DEFAULT_SOCIAL_IMAGE.url}`,
    datePublished: entry.date,
    authorName: company.name,
  });
  const breadcrumbJsonLd = buildBreadcrumbJsonLd([
    { name: "Home", url: SITE_URL },
    { name: "Changelog", url: `${SITE_URL}/changelog` },
    { name: company.name, url: `${SITE_URL}/changelog/${name}` },
    { name: entry.title, url },
  ]);

  return (
    <div className="mx-auto w-full max-w-[760px] px-4 pt-24 sm:px-6 sm:pt-28 md:px-8 md:pt-32 lg:px-0">
      <script
        // biome-ignore lint/security/noDangerouslySetInnerHtml: server-built JSON-LD
        dangerouslySetInnerHTML={{ __html: serializeJsonLd(articleJsonLd) }}
        type="application/ld+json"
      />
      <script
        // biome-ignore lint/security/noDangerouslySetInnerHtml: server-built JSON-LD
        dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbJsonLd) }}
        type="application/ld+json"
      />
      <Link
        className="text-foreground/50 hover:text-foreground mb-6 inline-flex items-center gap-1 font-sans text-sm transition-colors"
        href={`/changelog/${name}`}
      >
        &larr; {company.name}
      </Link>

      <h1 className="font-display text-3xl font-semibold tracking-[-0.02em] text-[#1E1E1E] sm:text-4xl dark:text-white">
        {entry.title}
      </h1>
      <time className="text-foreground/40 mt-2 block font-sans text-sm">
        {formatChangelogDate(entry.date)}
      </time>

      <div className="mt-4 flex items-center gap-1.5">
        <span className="text-primary">
          <NotraMark className="size-3.5 shrink-0" />
        </span>
        <p className="text-muted-foreground font-sans text-xs">
          This changelog is generated by Notra for demonstration purposes. Notra
          is not affiliated with {company.name}.
        </p>
      </div>

      <article className="prose prose-neutral dark:prose-invert prose-headings:font-sans prose-headings:font-semibold prose-p:font-sans prose-a:text-primary prose-li:text-foreground/80 prose-p:text-foreground/80 prose-strong:text-foreground prose-p:leading-7 prose-headings:tracking-tight prose-a:no-underline hover:prose-a:underline mt-8 max-w-none">
        <TableOfContents toc={entry.toc} />
        <MDX components={getMDXComponents()} />
      </article>

      <div className="mt-12 flex items-center gap-2">
        <Link
          className="text-muted-foreground hover:text-foreground flex items-center gap-2 transition-colors"
          href={`/?utm_source=showcase&utm_medium=referral&utm_campaign=${name}`}
        >
          <span className="text-primary">
            <NotraMark className="size-4 shrink-0" />
          </span>
          <span className="font-sans text-xs font-medium">
            Powered by Notra
          </span>
        </Link>
      </div>
    </div>
  );
}
