import type { CitationRow } from "@/types/landing/geo";

export const HERO_COLLAGE_CITATION_HEADERS = {
  when: "When",
  provider: "Provider",
  path: "Path",
  purpose: "Purpose",
};

export const HERO_COLLAGE_CITATION_ROWS: CitationRow[] = [
  {
    id: "c-1",
    agoSeconds: 2,
    provider: "ChatGPT-User",
    engine: "chatgpt",
    path: "/blog/geo-guide",
    purpose: "assistant-browse",
  },
  {
    id: "c-2",
    agoSeconds: 9,
    provider: "PerplexityBot",
    engine: "perplexity",
    path: "/docs/sdk",
    purpose: "search-index",
  },
  {
    id: "c-3",
    agoSeconds: 14,
    provider: "Claude-User",
    engine: "claude",
    path: "/pricing",
    purpose: "assistant-browse",
  },
  {
    id: "c-4",
    agoSeconds: 31,
    provider: "GPTBot",
    engine: "chatgpt",
    path: "/changelog",
    purpose: "training-crawler",
  },
  {
    id: "c-5",
    agoSeconds: 48,
    provider: "Perplexity",
    engine: "perplexity",
    path: "/integrations",
    purpose: "assistant-referral",
  },
  {
    id: "c-6",
    agoSeconds: 60,
    provider: "ClaudeBot",
    engine: "claude",
    path: "/llms.txt",
    purpose: "training-crawler",
    markdown: true,
  },
  {
    id: "c-7",
    agoSeconds: 120,
    provider: "Gemini",
    engine: "gemini",
    path: "/docs/sdk/quickstart",
    purpose: "assistant-browse",
  },
  {
    id: "c-8",
    agoSeconds: 120,
    provider: "OAI-SearchBot",
    engine: "chatgpt",
    path: "/customers/saas",
    purpose: "search-index",
  },
  {
    id: "c-9",
    agoSeconds: 180,
    provider: "KimiBot",
    engine: "kimi",
    path: "/blog/ai-search-visibility",
    purpose: "search-index",
  },
  {
    id: "c-10",
    agoSeconds: 240,
    provider: "ChatGPT",
    engine: "chatgpt",
    path: "/pricing",
    purpose: "assistant-referral",
  },
  {
    id: "c-11",
    agoSeconds: 300,
    provider: "ChatGLM-Spider",
    engine: "glm",
    path: "/blog/geo-guide",
    purpose: "training-crawler",
  },
  {
    id: "c-12",
    agoSeconds: 360,
    provider: "Claude Code",
    engine: "claude-code",
    path: "/llms-full.txt",
    purpose: "assistant-browse",
    markdown: true,
  },
];
