/**
 * Categories for the public "State of AI Search" reports on usenotra.com.
 * Each brand is matched as a whole word; `caseSensitive` guards names that are
 * also common English words ("Render", "Profound", "Loops").
 */

export interface ReportBrand {
  name: string;
  domain: string;
  aliases?: string[];
  caseSensitive?: boolean;
}

export interface ReportCategory {
  slug: string;
  subject: string;
  /** Completes "who they think is the best …". */
  noun: string;
  /** Google query whose AI Overview is shown in full on the report. */
  headQuery: string;
  prompts: string[];
  brands: ReportBrand[];
}

export const REPORT_CATEGORIES: ReportCategory[] = [
  {
    slug: "ai-visibility",
    subject: "AI visibility",
    noun: "AI search visibility tool",
    headQuery: "best ai search visibility tool",
    prompts: [
      "best ai search visibility tool",
      "how do i track if chatgpt recommends my product",
      "what's the best tool to monitor brand mentions in ai answers",
      "best generative engine optimization (GEO) software for a startup",
      "which tools track visibility in google ai overviews",
      "how can i see what claude and chatgpt say about my company",
      "best alternative to semrush for ai search tracking",
      "i run a b2b saas, how do i measure our share of voice in llm answers",
      "what's the cheapest way to track ai search rankings",
      "best llm brand monitoring tool for agencies",
      "how do i get my saas recommended by chatgpt",
      "tools that show which sources ai assistants cite for my category",
      "profound vs peec ai, which is better",
      "what software do marketers use for answer engine optimization",
      "best ai visibility tracker with content recommendations",
    ],
    brands: [
      { name: "Profound", domain: "tryprofound.com", caseSensitive: true },
      { name: "Peec AI", domain: "peec.ai", aliases: ["Peec"] },
      {
        name: "Otterly.AI",
        domain: "otterly.ai",
        aliases: ["Otterly", "OtterlyAI"],
      },
      { name: "Scrunch", domain: "scrunch.com", aliases: ["Scrunch AI"] },
      { name: "AthenaHQ", domain: "athenahq.ai", aliases: ["Athena HQ"] },
      { name: "Semrush", domain: "semrush.com", aliases: ["SEMrush"] },
      { name: "Ahrefs", domain: "ahrefs.com", aliases: ["Brand Radar"] },
      { name: "Writesonic", domain: "writesonic.com" },
      { name: "ZipTie", domain: "ziptie.dev", aliases: ["ZipTie.dev"] },
      { name: "Rankscale", domain: "rankscale.ai" },
      { name: "Evertune", domain: "evertune.ai" },
      { name: "SE Ranking", domain: "seranking.com", aliases: ["SE Visible"] },
      { name: "ByDefault", domain: "bydefault.so", caseSensitive: true },
      { name: "Notra", domain: "usenotra.com", caseSensitive: true },
      {
        name: "HubSpot AI Search Grader",
        domain: "hubspot.com",
        aliases: ["AI Search Grader", "HubSpot AEO", "HubSpot"],
      },
    ],
  },
  {
    slug: "changelog",
    subject: "Changelog",
    noun: "changelog tool",
    headQuery: "best changelog tool for saas",
    prompts: [
      "best changelog tool for saas",
      "what should i use to publish product release notes",
      "how do i add an in-app changelog widget to my web app",
      "best way to announce new features to users",
      "tools that write release notes from github commits automatically",
      "beamer alternatives that are cheaper",
      "what's the best public roadmap and changelog tool",
      "how do startups keep a changelog page up to date",
      "best changelog software with email notifications",
      "i need a changelog for my developer tool, what do people use",
      "ai tool that turns pull requests into changelog posts",
      "best product update announcement tool for b2b saas",
      "headway vs beamer vs launchnotes",
      "free changelog page for a small startup",
      "how to automate release notes for a mobile app",
    ],
    brands: [
      { name: "Beamer", domain: "getbeamer.com" },
      { name: "Headway", domain: "headwayapp.co", caseSensitive: true },
      { name: "LaunchNotes", domain: "launchnotes.com" },
      { name: "Canny", domain: "canny.io", caseSensitive: true },
      { name: "Featurebase", domain: "featurebase.app" },
      { name: "AnnounceKit", domain: "announcekit.app" },
      { name: "Frill", domain: "frill.co", caseSensitive: true },
      { name: "Productlane", domain: "productlane.com" },
      { name: "Noticeable", domain: "noticeable.io", caseSensitive: true },
      { name: "Sleekplan", domain: "sleekplan.com" },
      { name: "GitHub Releases", domain: "github.com" },
      { name: "Changelogfy", domain: "changelogfy.com" },
      {
        name: "Release Drafter",
        domain: "github.com",
        aliases: ["release-drafter"],
      },
      { name: "Mintlify", domain: "mintlify.com" },
      { name: "Notra", domain: "usenotra.com", caseSensitive: true },
    ],
  },
  {
    slug: "email-api",
    subject: "Email API",
    noun: "transactional email API",
    headQuery: "best transactional email api",
    prompts: [
      "best transactional email api",
      "what should i use to send emails from my next.js app",
      "cheapest reliable email api for a startup",
      "sendgrid alternatives with better deliverability",
      "which email api has the best developer experience",
      "how do i send password reset emails from node",
      "best email service for saas onboarding emails",
      "resend vs postmark vs sendgrid",
      "what email provider should i use for high volume transactional email",
      "best email api with react email templates",
      "i need to send receipts and notifications from my app, what service",
      "which email api is best for deliverability to gmail",
      "best smtp service for a django app",
      "what's the easiest way to send emails from a serverless function",
      "best email api for product and marketing emails in one place",
    ],
    brands: [
      { name: "Resend", domain: "resend.com", caseSensitive: true },
      {
        name: "SendGrid",
        domain: "sendgrid.com",
        aliases: ["Twilio SendGrid"],
      },
      { name: "Postmark", domain: "postmarkapp.com", caseSensitive: true },
      { name: "Mailgun", domain: "mailgun.com" },
      {
        name: "Amazon SES",
        domain: "aws.amazon.com",
        aliases: ["AWS SES", "SES", "Simple Email Service"],
      },
      { name: "Brevo", domain: "brevo.com", aliases: ["Sendinblue"] },
      { name: "MailerSend", domain: "mailersend.com" },
      { name: "SparkPost", domain: "sparkpost.com" },
      { name: "Mailtrap", domain: "mailtrap.io" },
      { name: "Loops", domain: "loops.so", caseSensitive: true },
      { name: "Plunk", domain: "useplunk.com", caseSensitive: true },
      {
        name: "Mailchimp Transactional",
        domain: "mailchimp.com",
        aliases: ["Mandrill"],
      },
      { name: "Customer.io", domain: "customer.io" },
      { name: "ZeptoMail", domain: "zeptomail.com" },
      {
        name: "Bird",
        domain: "bird.com",
        aliases: ["MessageBird"],
        caseSensitive: true,
      },
    ],
  },
  {
    slug: "postgres",
    subject: "Postgres",
    noun: "Postgres provider",
    headQuery: "best postgres hosting",
    prompts: [
      "best postgres hosting",
      "what's the best postgres provider",
      "what's the best serverless postgres right now",
      "i'm building an ai app and need postgres with pgvector, what should i use",
      "which managed postgres has the most reliable backups and uptime",
      "what's the best postgres host for a small team with no devops person",
      "how do i get a postgres database for my django app",
      "what's the easiest way to spin up postgres for a prototype",
      "which postgres provider scales best when my app grows",
      "is it worth paying for managed postgres or should i just self-host it",
      "i need postgres for my saas, what should i use",
      "which postgres host has the best free tier",
      "best postgres for a next.js app",
      "best managed postgres for an early stage startup",
      "cheapest managed postgres in europe",
    ],
    brands: [
      { name: "Neon", domain: "neon.com", caseSensitive: true },
      { name: "Supabase", domain: "supabase.com" },
      {
        name: "Amazon RDS",
        domain: "aws.amazon.com",
        aliases: ["AWS RDS", "Aurora", "RDS"],
      },
      { name: "Render", domain: "render.com", caseSensitive: true },
      { name: "Railway", domain: "railway.com", caseSensitive: true },
      {
        name: "DigitalOcean",
        domain: "digitalocean.com",
        aliases: ["Digital Ocean"],
      },
      {
        name: "Google Cloud SQL",
        domain: "cloud.google.com",
        aliases: ["Cloud SQL", "AlloyDB"],
      },
      { name: "Aiven", domain: "aiven.io" },
      {
        name: "Crunchy Data",
        domain: "crunchydata.com",
        aliases: ["Crunchy Bridge"],
      },
      {
        name: "Azure Database for PostgreSQL",
        domain: "azure.microsoft.com",
        aliases: ["Azure Database", "Azure PostgreSQL", "Azure Postgres"],
      },
      { name: "Prisma Postgres", domain: "prisma.io" },
      { name: "Heroku", domain: "heroku.com" },
      { name: "PlanetScale", domain: "planetscale.com" },
      { name: "Xata", domain: "xata.io" },
      { name: "Tiger Data", domain: "tigerdata.com", aliases: ["Timescale"] },
    ],
  },
  {
    slug: "auth",
    subject: "Auth",
    noun: "auth provider",
    headQuery: "best authentication provider for saas",
    prompts: [
      "best authentication provider for saas",
      "what's the best auth for a next.js app",
      "clerk vs auth0 vs workos",
      "which auth provider is best for b2b saas with sso",
      "cheapest auth provider for a startup with lots of users",
      "should i build my own auth or use a service",
      "best open source authentication library",
      "how do i add login with google to my react app",
      "best auth provider with passkeys and mfa",
      "auth0 alternatives that are cheaper",
      "what auth should i use with supabase or firebase",
      "best enterprise sso and scim provider for startups",
      "easiest way to add authentication to a mobile app",
      "best self-hosted identity provider",
      "which auth service has the best developer experience",
    ],
    brands: [
      { name: "Clerk", domain: "clerk.com", caseSensitive: true },
      { name: "Auth0", domain: "auth0.com" },
      { name: "Supabase Auth", domain: "supabase.com", aliases: ["Supabase"] },
      {
        name: "Firebase Authentication",
        domain: "firebase.google.com",
        aliases: ["Firebase Auth", "Firebase"],
      },
      { name: "WorkOS", domain: "workos.com" },
      { name: "Okta", domain: "okta.com" },
      { name: "Keycloak", domain: "keycloak.org" },
      {
        name: "Amazon Cognito",
        domain: "aws.amazon.com",
        aliases: ["AWS Cognito", "Cognito"],
      },
      {
        name: "Better Auth",
        domain: "better-auth.com",
        aliases: ["BetterAuth"],
      },
      { name: "Kinde", domain: "kinde.com" },
      { name: "Stytch", domain: "stytch.com" },
      {
        name: "Auth.js",
        domain: "authjs.dev",
        aliases: ["NextAuth", "NextAuth.js"],
      },
      { name: "Descope", domain: "descope.com" },
      { name: "SuperTokens", domain: "supertokens.com" },
      { name: "FusionAuth", domain: "fusionauth.io" },
    ],
  },
  {
    slug: "app-hosting",
    subject: "App hosting",
    noun: "app hosting platform",
    headQuery: "best app hosting platform for developers",
    prompts: [
      "best app hosting platform for developers",
      "where should i deploy my next.js app",
      "best heroku alternative",
      "cheapest way to host a node.js backend",
      "vercel vs netlify vs cloudflare pages",
      "best platform to deploy a python api",
      "where do i host a full stack app with a database",
      "best hosting for a side project with a free tier",
      "which hosting platform scales best for a growing saas",
      "how do i deploy a docker container without managing servers",
      "best european cloud hosting for a startup",
      "render vs railway vs fly.io",
      "best platform to host background workers and cron jobs",
      "what's the easiest way to deploy a web app in 2026",
      "best self-hosted paas",
    ],
    brands: [
      { name: "Render", domain: "render.com", caseSensitive: true },
      { name: "Railway", domain: "railway.com", caseSensitive: true },
      { name: "Vercel", domain: "vercel.com" },
      {
        name: "AWS",
        domain: "aws.amazon.com",
        aliases: ["Amazon Web Services", "Elastic Beanstalk", "App Runner"],
        caseSensitive: true,
      },
      {
        name: "Fly.io",
        domain: "fly.io",
        aliases: ["Fly"],
        caseSensitive: true,
      },
      {
        name: "Cloudflare",
        domain: "cloudflare.com",
        aliases: ["Cloudflare Workers", "Cloudflare Pages"],
      },
      {
        name: "DigitalOcean",
        domain: "digitalocean.com",
        aliases: ["Digital Ocean", "App Platform"],
      },
      { name: "Netlify", domain: "netlify.com" },
      { name: "Hetzner", domain: "hetzner.com" },
      {
        name: "Google Cloud",
        domain: "cloud.google.com",
        aliases: ["Cloud Run", "GCP", "App Engine"],
      },
      {
        name: "Azure",
        domain: "azure.microsoft.com",
        aliases: ["Azure App Service"],
        caseSensitive: true,
      },
      { name: "Heroku", domain: "heroku.com" },
      { name: "Coolify", domain: "coolify.io" },
      {
        name: "Firebase",
        domain: "firebase.google.com",
        aliases: ["Firebase Hosting"],
      },
      { name: "Northflank", domain: "northflank.com" },
    ],
  },
];
