/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as ApiHealthcheckRouteImport } from './routes/api.healthcheck'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as ApiSessionRouteImport } from './routes/api.session'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthExternalRouteImport } from './routes/auth.external'
import { Route as AuthInitiateRouteImport } from './routes/auth.initiate'
import { Route as RpcIndexRouteImport } from './routes/rpc.index'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as ApiAutumnSplatRouteImport } from './routes/api.autumn.$'
import { Route as ApiBrandFontCssRouteImport } from './routes/api.brand-font.css'
import { Route as ApiBrandFontFileRouteImport } from './routes/api.brand-font.file'
import { Route as ApiCommandPaletteNavigateRouteImport } from './routes/api.command-palette.navigate'
import { Route as ApiCronBrewContactsRouteImport } from './routes/api.cron.brew-contacts'
import { Route as ApiCronDailySummaryRouteImport } from './routes/api.cron.daily-summary'
import { Route as ApiCronGeoContentGapsRouteImport } from './routes/api.cron.geo-content-gaps'
import { Route as ApiCronGeoScanRouteImport } from './routes/api.cron.geo-scan'
import { Route as ApiCronMonitoringRouteImport } from './routes/api.cron.monitoring'
import { Route as ApiCronScheduledPublicationsRouteImport } from './routes/api.cron.scheduled-publications'
import { Route as ApiDemoEnterRouteImport } from './routes/api.demo.enter'
import { Route as ApiDemoRequestsRouteImport } from './routes/api.demo.requests'
import { Route as ApiDemoSandboxRouteImport } from './routes/api.demo.sandbox'
import { Route as ApiGeoIngestRouteImport } from './routes/api.geo.ingest'
import { Route as ApiSocialAccountsCallbackRouteImport } from './routes/api.social-accounts.callback'
import { Route as ApiUploadsContentImageRouteImport } from './routes/api.uploads.content-image'
import { Route as ApiUploadsConvertHeicRouteImport } from './routes/api.uploads.convert-heic'
import { Route as ApiWebhooksWorkosRouteImport } from './routes/api.webhooks.workos'
import { Route as ApiWorkflowsGscSyncRouteImport } from './routes/api.workflows.gsc-sync'
import { Route as ApiWorkflowsIrisRouteImport } from './routes/api.workflows.iris'
import { Route as ApiWorkflowsScheduleRouteImport } from './routes/api.workflows.schedule'
import { Route as ApiWorkflowsScheduledPublicationWakeRouteImport } from './routes/api.workflows.scheduled-publication-wake'
import { Route as ApiWorkflowsSocialAnalyticsSyncRouteImport } from './routes/api.workflows.social-analytics-sync'
import { Route as AuthSocialCallbackRouteImport } from './routes/auth.social.callback'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known.oauth-authorization-server.api.auth'
import { Route as ApiDemoRequestsRequestIdRouteImport } from './routes/api.demo.requests.$requestId'
import { Route as ApiDemoSandboxCustomizeRouteImport } from './routes/api.demo.sandbox.customize'
import { Route as ApiDemoSandboxInfoRouteImport } from './routes/api.demo.sandbox.info'
import { Route as ApiDemoSandboxResetRouteImport } from './routes/api.demo.sandbox.reset'
import { Route as ApiDemoSandboxTimezoneRouteImport } from './routes/api.demo.sandbox.timezone'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api.integrations.github.callback'
import { Route as ApiIntegrationsGoogleSearchConsoleAuthorizeRouteImport } from './routes/api.integrations.google-search-console.authorize'
import { Route as ApiIntegrationsGoogleSearchConsoleCallbackRouteImport } from './routes/api.integrations.google-search-console.callback'
import { Route as ApiIntegrationsLinearAuthorizeRouteImport } from './routes/api.integrations.linear.authorize'
import { Route as ApiIntegrationsLinearCallbackRouteImport } from './routes/api.integrations.linear.callback'
import { Route as ApiIntegrationsSlackAuthorizeRouteImport } from './routes/api.integrations.slack.authorize'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api.integrations.slack.callback'
import { Route as ApiInternalContentScheduledPublicationAttemptRouteImport } from './routes/api.internal.content.scheduled-publication-attempt'
import { Route as ApiInternalContentSyncGithubRouteImport } from './routes/api.internal.content.sync-github'
import { Route as ApiInternalGeoSequenceRunRouteImport } from './routes/api.internal.geo.sequence-run'
import { Route as ApiInternalGeoWriterPlanRouteImport } from './routes/api.internal.geo.writer-plan'
import { Route as ApiInternalWorkflowsAgentReadinessRouteImport } from './routes/api.internal.workflows.agent-readiness'
import { Route as ApiInternalWorkflowsBrandAnalysisRouteImport } from './routes/api.internal.workflows.brand-analysis'
import { Route as ApiInternalWorkflowsContentPublicationSyncRepairRouteImport } from './routes/api.internal.workflows.content-publication-sync-repair'
import { Route as ApiInternalWorkflowsGeoScanRouteImport } from './routes/api.internal.workflows.geo-scan'
import { Route as ApiInternalWorkflowsGeoWriterRouteImport } from './routes/api.internal.workflows.geo-writer'
import { Route as ApiInternalWorkflowsOnDemandContentRouteImport } from './routes/api.internal.workflows.on-demand-content'
import { Route as ApiOrganizationsOrganizationIdChatRouteImport } from './routes/api.organizations.$organizationId.chat'
import { Route as ApiUploadsContentImagesSplatRouteImport } from './routes/api.uploads.content-images.$'
import { Route as ApiWebhooksGithubAppRouteImport } from './routes/api.webhooks.github.app'
import { Route as ApiIntegrationsMcpOauthCallbackRouteImport } from './routes/api.integrations.mcp.oauth.callback'
import { Route as ApiOrganizationsOrganizationIdAgentSplatRouteImport } from './routes/api.organizations.$organizationId.agent.$'
import { Route as ApiOrganizationsOrganizationIdDashboardAgentChatRouteImport } from './routes/api.organizations.$organizationId.dashboard-agent.chat'
import { Route as ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRouteImport } from './routes/api.organizations.$organizationId.chat.$chatId.mirror-stream'
import { Route as ApiOrganizationsOrganizationIdChatChatIdRelayRouteImport } from './routes/api.organizations.$organizationId.chat.$chatId.relay'
import { Route as ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRouteImport } from './routes/api.organizations.$organizationId.chat.$chatId.relay-approval'
import { Route as ApiOrganizationsOrganizationIdChatChatIdStopRouteImport } from './routes/api.organizations.$organizationId.chat.$chatId.stop'
import { Route as ApiOrganizationsOrganizationIdChatChatIdStreamRouteImport } from './routes/api.organizations.$organizationId.chat.$chatId.stream'
import { Route as ApiOrganizationsOrganizationIdContentContentIdChatRouteImport } from './routes/api.organizations.$organizationId.content.$contentId.chat'
import { Route as ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRouteImport } from './routes/api.organizations.$organizationId.dashboard-agent.chat.$chatId'
import { Route as ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRouteImport } from './routes/api.webhooks.$provider.$organizationId.$integrationId.$repositoryId'
import { Route as ApiOrganizationsOrganizationIdContentContentIdChatChatIdRouteImport } from './routes/api.organizations.$organizationId.content.$contentId.chat.$chatId'

const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExternalRoute = AuthExternalRouteImport.update({
  id: '/auth/external',
  path: '/auth/external',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInitiateRoute = AuthInitiateRouteImport.update({
  id: '/auth/initiate',
  path: '/auth/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcIndexRoute = RpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandFontCssRoute = ApiBrandFontCssRouteImport.update({
  id: '/api/brand-font/css',
  path: '/api/brand-font/css',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandFontFileRoute = ApiBrandFontFileRouteImport.update({
  id: '/api/brand-font/file',
  path: '/api/brand-font/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommandPaletteNavigateRoute =
  ApiCommandPaletteNavigateRouteImport.update({
    id: '/api/command-palette/navigate',
    path: '/api/command-palette/navigate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronBrewContactsRoute = ApiCronBrewContactsRouteImport.update({
  id: '/api/cron/brew-contacts',
  path: '/api/cron/brew-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailySummaryRoute = ApiCronDailySummaryRouteImport.update({
  id: '/api/cron/daily-summary',
  path: '/api/cron/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGeoContentGapsRoute = ApiCronGeoContentGapsRouteImport.update({
  id: '/api/cron/geo-content-gaps',
  path: '/api/cron/geo-content-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGeoScanRoute = ApiCronGeoScanRouteImport.update({
  id: '/api/cron/geo-scan',
  path: '/api/cron/geo-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMonitoringRoute = ApiCronMonitoringRouteImport.update({
  id: '/api/cron/monitoring',
  path: '/api/cron/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScheduledPublicationsRoute =
  ApiCronScheduledPublicationsRouteImport.update({
    id: '/api/cron/scheduled-publications',
    path: '/api/cron/scheduled-publications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDemoEnterRoute = ApiDemoEnterRouteImport.update({
  id: '/api/demo/enter',
  path: '/api/demo/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRequestsRoute = ApiDemoRequestsRouteImport.update({
  id: '/api/demo/requests',
  path: '/api/demo/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoSandboxRoute = ApiDemoSandboxRouteImport.update({
  id: '/api/demo/sandbox',
  path: '/api/demo/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoIngestRoute = ApiGeoIngestRouteImport.update({
  id: '/api/geo/ingest',
  path: '/api/geo/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialAccountsCallbackRoute =
  ApiSocialAccountsCallbackRouteImport.update({
    id: '/api/social-accounts/callback',
    path: '/api/social-accounts/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadsContentImageRoute = ApiUploadsContentImageRouteImport.update({
  id: '/api/uploads/content-image',
  path: '/api/uploads/content-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsConvertHeicRoute = ApiUploadsConvertHeicRouteImport.update({
  id: '/api/uploads/convert-heic',
  path: '/api/uploads/convert-heic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWorkosRoute = ApiWebhooksWorkosRouteImport.update({
  id: '/api/webhooks/workos',
  path: '/api/webhooks/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsGscSyncRoute = ApiWorkflowsGscSyncRouteImport.update({
  id: '/api/workflows/gsc-sync',
  path: '/api/workflows/gsc-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsIrisRoute = ApiWorkflowsIrisRouteImport.update({
  id: '/api/workflows/iris',
  path: '/api/workflows/iris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsScheduleRoute = ApiWorkflowsScheduleRouteImport.update({
  id: '/api/workflows/schedule',
  path: '/api/workflows/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsScheduledPublicationWakeRoute =
  ApiWorkflowsScheduledPublicationWakeRouteImport.update({
    id: '/api/workflows/scheduled-publication-wake',
    path: '/api/workflows/scheduled-publication-wake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSocialAnalyticsSyncRoute =
  ApiWorkflowsSocialAnalyticsSyncRouteImport.update({
    id: '/api/workflows/social-analytics-sync',
    path: '/api/workflows/social-analytics-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSocialCallbackRoute = AuthSocialCallbackRouteImport.update({
  id: '/auth/social/callback',
  path: '/auth/social/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)
const ApiDemoRequestsRequestIdRoute =
  ApiDemoRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => ApiDemoRequestsRoute,
  } as any)
const ApiDemoSandboxCustomizeRoute = ApiDemoSandboxCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => ApiDemoSandboxRoute,
} as any)
const ApiDemoSandboxInfoRoute = ApiDemoSandboxInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ApiDemoSandboxRoute,
} as any)
const ApiDemoSandboxResetRoute = ApiDemoSandboxResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ApiDemoSandboxRoute,
} as any)
const ApiDemoSandboxTimezoneRoute = ApiDemoSandboxTimezoneRouteImport.update({
  id: '/timezone',
  path: '/timezone',
  getParentRoute: () => ApiDemoSandboxRoute,
} as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSearchConsoleAuthorizeRoute =
  ApiIntegrationsGoogleSearchConsoleAuthorizeRouteImport.update({
    id: '/api/integrations/google-search-console/authorize',
    path: '/api/integrations/google-search-console/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSearchConsoleCallbackRoute =
  ApiIntegrationsGoogleSearchConsoleCallbackRouteImport.update({
    id: '/api/integrations/google-search-console/callback',
    path: '/api/integrations/google-search-console/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinearAuthorizeRoute =
  ApiIntegrationsLinearAuthorizeRouteImport.update({
    id: '/api/integrations/linear/authorize',
    path: '/api/integrations/linear/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinearCallbackRoute =
  ApiIntegrationsLinearCallbackRouteImport.update({
    id: '/api/integrations/linear/callback',
    path: '/api/integrations/linear/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackAuthorizeRoute =
  ApiIntegrationsSlackAuthorizeRouteImport.update({
    id: '/api/integrations/slack/authorize',
    path: '/api/integrations/slack/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalContentScheduledPublicationAttemptRoute =
  ApiInternalContentScheduledPublicationAttemptRouteImport.update({
    id: '/api/internal/content/scheduled-publication-attempt',
    path: '/api/internal/content/scheduled-publication-attempt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalContentSyncGithubRoute =
  ApiInternalContentSyncGithubRouteImport.update({
    id: '/api/internal/content/sync-github',
    path: '/api/internal/content/sync-github',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGeoSequenceRunRoute =
  ApiInternalGeoSequenceRunRouteImport.update({
    id: '/api/internal/geo/sequence-run',
    path: '/api/internal/geo/sequence-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGeoWriterPlanRoute =
  ApiInternalGeoWriterPlanRouteImport.update({
    id: '/api/internal/geo/writer-plan',
    path: '/api/internal/geo/writer-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsAgentReadinessRoute =
  ApiInternalWorkflowsAgentReadinessRouteImport.update({
    id: '/api/internal/workflows/agent-readiness',
    path: '/api/internal/workflows/agent-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsBrandAnalysisRoute =
  ApiInternalWorkflowsBrandAnalysisRouteImport.update({
    id: '/api/internal/workflows/brand-analysis',
    path: '/api/internal/workflows/brand-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsContentPublicationSyncRepairRoute =
  ApiInternalWorkflowsContentPublicationSyncRepairRouteImport.update({
    id: '/api/internal/workflows/content-publication-sync-repair',
    path: '/api/internal/workflows/content-publication-sync-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsGeoScanRoute =
  ApiInternalWorkflowsGeoScanRouteImport.update({
    id: '/api/internal/workflows/geo-scan',
    path: '/api/internal/workflows/geo-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsGeoWriterRoute =
  ApiInternalWorkflowsGeoWriterRouteImport.update({
    id: '/api/internal/workflows/geo-writer',
    path: '/api/internal/workflows/geo-writer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWorkflowsOnDemandContentRoute =
  ApiInternalWorkflowsOnDemandContentRouteImport.update({
    id: '/api/internal/workflows/on-demand-content',
    path: '/api/internal/workflows/on-demand-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdChatRoute =
  ApiOrganizationsOrganizationIdChatRouteImport.update({
    id: '/api/organizations/$organizationId/chat',
    path: '/api/organizations/$organizationId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadsContentImagesSplatRoute =
  ApiUploadsContentImagesSplatRouteImport.update({
    id: '/api/uploads/content-images/$',
    path: '/api/uploads/content-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksGithubAppRoute = ApiWebhooksGithubAppRouteImport.update({
  id: '/api/webhooks/github/app',
  path: '/api/webhooks/github/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsMcpOauthCallbackRoute =
  ApiIntegrationsMcpOauthCallbackRouteImport.update({
    id: '/api/integrations/mcp/oauth/callback',
    path: '/api/integrations/mcp/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdAgentSplatRoute =
  ApiOrganizationsOrganizationIdAgentSplatRouteImport.update({
    id: '/api/organizations/$organizationId/agent/$',
    path: '/api/organizations/$organizationId/agent/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdDashboardAgentChatRoute =
  ApiOrganizationsOrganizationIdDashboardAgentChatRouteImport.update({
    id: '/api/organizations/$organizationId/dashboard-agent/chat',
    path: '/api/organizations/$organizationId/dashboard-agent/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute =
  ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRouteImport.update({
    id: '/$chatId/mirror-stream',
    path: '/$chatId/mirror-stream',
    getParentRoute: () => ApiOrganizationsOrganizationIdChatRoute,
  } as any)
const ApiOrganizationsOrganizationIdChatChatIdRelayRoute =
  ApiOrganizationsOrganizationIdChatChatIdRelayRouteImport.update({
    id: '/$chatId/relay',
    path: '/$chatId/relay',
    getParentRoute: () => ApiOrganizationsOrganizationIdChatRoute,
  } as any)
const ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute =
  ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRouteImport.update({
    id: '/$chatId/relay-approval',
    path: '/$chatId/relay-approval',
    getParentRoute: () => ApiOrganizationsOrganizationIdChatRoute,
  } as any)
const ApiOrganizationsOrganizationIdChatChatIdStopRoute =
  ApiOrganizationsOrganizationIdChatChatIdStopRouteImport.update({
    id: '/$chatId/stop',
    path: '/$chatId/stop',
    getParentRoute: () => ApiOrganizationsOrganizationIdChatRoute,
  } as any)
const ApiOrganizationsOrganizationIdChatChatIdStreamRoute =
  ApiOrganizationsOrganizationIdChatChatIdStreamRouteImport.update({
    id: '/$chatId/stream',
    path: '/$chatId/stream',
    getParentRoute: () => ApiOrganizationsOrganizationIdChatRoute,
  } as any)
const ApiOrganizationsOrganizationIdContentContentIdChatRoute =
  ApiOrganizationsOrganizationIdContentContentIdChatRouteImport.update({
    id: '/api/organizations/$organizationId/content/$contentId/chat',
    path: '/api/organizations/$organizationId/content/$contentId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute =
  ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => ApiOrganizationsOrganizationIdDashboardAgentChatRoute,
  } as any)
const ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute =
  ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRouteImport.update({
    id: '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId',
    path: '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute =
  ApiOrganizationsOrganizationIdContentContentIdChatChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () =>
      ApiOrganizationsOrganizationIdContentContentIdChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/image': typeof ApiImageRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/external': typeof AuthExternalRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/brand-font/css': typeof ApiBrandFontCssRoute
  '/api/brand-font/file': typeof ApiBrandFontFileRoute
  '/api/command-palette/navigate': typeof ApiCommandPaletteNavigateRoute
  '/api/cron/brew-contacts': typeof ApiCronBrewContactsRoute
  '/api/cron/daily-summary': typeof ApiCronDailySummaryRoute
  '/api/cron/geo-content-gaps': typeof ApiCronGeoContentGapsRoute
  '/api/cron/geo-scan': typeof ApiCronGeoScanRoute
  '/api/cron/monitoring': typeof ApiCronMonitoringRoute
  '/api/cron/scheduled-publications': typeof ApiCronScheduledPublicationsRoute
  '/api/demo/enter': typeof ApiDemoEnterRoute
  '/api/demo/requests': typeof ApiDemoRequestsRouteWithChildren
  '/api/demo/sandbox': typeof ApiDemoSandboxRouteWithChildren
  '/api/geo/ingest': typeof ApiGeoIngestRoute
  '/api/social-accounts/callback': typeof ApiSocialAccountsCallbackRoute
  '/api/uploads/content-image': typeof ApiUploadsContentImageRoute
  '/api/uploads/convert-heic': typeof ApiUploadsConvertHeicRoute
  '/api/webhooks/workos': typeof ApiWebhooksWorkosRoute
  '/api/workflows/gsc-sync': typeof ApiWorkflowsGscSyncRoute
  '/api/workflows/iris': typeof ApiWorkflowsIrisRoute
  '/api/workflows/schedule': typeof ApiWorkflowsScheduleRoute
  '/api/workflows/scheduled-publication-wake': typeof ApiWorkflowsScheduledPublicationWakeRoute
  '/api/workflows/social-analytics-sync': typeof ApiWorkflowsSocialAnalyticsSyncRoute
  '/auth/social/callback': typeof AuthSocialCallbackRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/api/demo/requests/$requestId': typeof ApiDemoRequestsRequestIdRoute
  '/api/demo/sandbox/customize': typeof ApiDemoSandboxCustomizeRoute
  '/api/demo/sandbox/info': typeof ApiDemoSandboxInfoRoute
  '/api/demo/sandbox/reset': typeof ApiDemoSandboxResetRoute
  '/api/demo/sandbox/timezone': typeof ApiDemoSandboxTimezoneRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/google-search-console/authorize': typeof ApiIntegrationsGoogleSearchConsoleAuthorizeRoute
  '/api/integrations/google-search-console/callback': typeof ApiIntegrationsGoogleSearchConsoleCallbackRoute
  '/api/integrations/linear/authorize': typeof ApiIntegrationsLinearAuthorizeRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/internal/content/scheduled-publication-attempt': typeof ApiInternalContentScheduledPublicationAttemptRoute
  '/api/internal/content/sync-github': typeof ApiInternalContentSyncGithubRoute
  '/api/internal/geo/sequence-run': typeof ApiInternalGeoSequenceRunRoute
  '/api/internal/geo/writer-plan': typeof ApiInternalGeoWriterPlanRoute
  '/api/internal/workflows/agent-readiness': typeof ApiInternalWorkflowsAgentReadinessRoute
  '/api/internal/workflows/brand-analysis': typeof ApiInternalWorkflowsBrandAnalysisRoute
  '/api/internal/workflows/content-publication-sync-repair': typeof ApiInternalWorkflowsContentPublicationSyncRepairRoute
  '/api/internal/workflows/geo-scan': typeof ApiInternalWorkflowsGeoScanRoute
  '/api/internal/workflows/geo-writer': typeof ApiInternalWorkflowsGeoWriterRoute
  '/api/internal/workflows/on-demand-content': typeof ApiInternalWorkflowsOnDemandContentRoute
  '/api/organizations/$organizationId/chat': typeof ApiOrganizationsOrganizationIdChatRouteWithChildren
  '/api/uploads/content-images/$': typeof ApiUploadsContentImagesSplatRoute
  '/api/webhooks/github/app': typeof ApiWebhooksGithubAppRoute
  '/api/integrations/mcp/oauth/callback': typeof ApiIntegrationsMcpOauthCallbackRoute
  '/api/organizations/$organizationId/agent/$': typeof ApiOrganizationsOrganizationIdAgentSplatRoute
  '/api/organizations/$organizationId/dashboard-agent/chat': typeof ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren
  '/api/organizations/$organizationId/chat/$chatId/mirror-stream': typeof ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute
  '/api/organizations/$organizationId/chat/$chatId/relay': typeof ApiOrganizationsOrganizationIdChatChatIdRelayRoute
  '/api/organizations/$organizationId/chat/$chatId/relay-approval': typeof ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute
  '/api/organizations/$organizationId/chat/$chatId/stop': typeof ApiOrganizationsOrganizationIdChatChatIdStopRoute
  '/api/organizations/$organizationId/chat/$chatId/stream': typeof ApiOrganizationsOrganizationIdChatChatIdStreamRoute
  '/api/organizations/$organizationId/content/$contentId/chat': typeof ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren
  '/api/organizations/$organizationId/dashboard-agent/chat/$chatId': typeof ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute
  '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId': typeof ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute
  '/api/organizations/$organizationId/content/$contentId/chat/$chatId': typeof ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute
}
export interface FileRoutesByTo {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/image': typeof ApiImageRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/external': typeof AuthExternalRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc': typeof RpcIndexRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/brand-font/css': typeof ApiBrandFontCssRoute
  '/api/brand-font/file': typeof ApiBrandFontFileRoute
  '/api/command-palette/navigate': typeof ApiCommandPaletteNavigateRoute
  '/api/cron/brew-contacts': typeof ApiCronBrewContactsRoute
  '/api/cron/daily-summary': typeof ApiCronDailySummaryRoute
  '/api/cron/geo-content-gaps': typeof ApiCronGeoContentGapsRoute
  '/api/cron/geo-scan': typeof ApiCronGeoScanRoute
  '/api/cron/monitoring': typeof ApiCronMonitoringRoute
  '/api/cron/scheduled-publications': typeof ApiCronScheduledPublicationsRoute
  '/api/demo/enter': typeof ApiDemoEnterRoute
  '/api/demo/requests': typeof ApiDemoRequestsRouteWithChildren
  '/api/demo/sandbox': typeof ApiDemoSandboxRouteWithChildren
  '/api/geo/ingest': typeof ApiGeoIngestRoute
  '/api/social-accounts/callback': typeof ApiSocialAccountsCallbackRoute
  '/api/uploads/content-image': typeof ApiUploadsContentImageRoute
  '/api/uploads/convert-heic': typeof ApiUploadsConvertHeicRoute
  '/api/webhooks/workos': typeof ApiWebhooksWorkosRoute
  '/api/workflows/gsc-sync': typeof ApiWorkflowsGscSyncRoute
  '/api/workflows/iris': typeof ApiWorkflowsIrisRoute
  '/api/workflows/schedule': typeof ApiWorkflowsScheduleRoute
  '/api/workflows/scheduled-publication-wake': typeof ApiWorkflowsScheduledPublicationWakeRoute
  '/api/workflows/social-analytics-sync': typeof ApiWorkflowsSocialAnalyticsSyncRoute
  '/auth/social/callback': typeof AuthSocialCallbackRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/api/demo/requests/$requestId': typeof ApiDemoRequestsRequestIdRoute
  '/api/demo/sandbox/customize': typeof ApiDemoSandboxCustomizeRoute
  '/api/demo/sandbox/info': typeof ApiDemoSandboxInfoRoute
  '/api/demo/sandbox/reset': typeof ApiDemoSandboxResetRoute
  '/api/demo/sandbox/timezone': typeof ApiDemoSandboxTimezoneRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/google-search-console/authorize': typeof ApiIntegrationsGoogleSearchConsoleAuthorizeRoute
  '/api/integrations/google-search-console/callback': typeof ApiIntegrationsGoogleSearchConsoleCallbackRoute
  '/api/integrations/linear/authorize': typeof ApiIntegrationsLinearAuthorizeRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/internal/content/scheduled-publication-attempt': typeof ApiInternalContentScheduledPublicationAttemptRoute
  '/api/internal/content/sync-github': typeof ApiInternalContentSyncGithubRoute
  '/api/internal/geo/sequence-run': typeof ApiInternalGeoSequenceRunRoute
  '/api/internal/geo/writer-plan': typeof ApiInternalGeoWriterPlanRoute
  '/api/internal/workflows/agent-readiness': typeof ApiInternalWorkflowsAgentReadinessRoute
  '/api/internal/workflows/brand-analysis': typeof ApiInternalWorkflowsBrandAnalysisRoute
  '/api/internal/workflows/content-publication-sync-repair': typeof ApiInternalWorkflowsContentPublicationSyncRepairRoute
  '/api/internal/workflows/geo-scan': typeof ApiInternalWorkflowsGeoScanRoute
  '/api/internal/workflows/geo-writer': typeof ApiInternalWorkflowsGeoWriterRoute
  '/api/internal/workflows/on-demand-content': typeof ApiInternalWorkflowsOnDemandContentRoute
  '/api/organizations/$organizationId/chat': typeof ApiOrganizationsOrganizationIdChatRouteWithChildren
  '/api/uploads/content-images/$': typeof ApiUploadsContentImagesSplatRoute
  '/api/webhooks/github/app': typeof ApiWebhooksGithubAppRoute
  '/api/integrations/mcp/oauth/callback': typeof ApiIntegrationsMcpOauthCallbackRoute
  '/api/organizations/$organizationId/agent/$': typeof ApiOrganizationsOrganizationIdAgentSplatRoute
  '/api/organizations/$organizationId/dashboard-agent/chat': typeof ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren
  '/api/organizations/$organizationId/chat/$chatId/mirror-stream': typeof ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute
  '/api/organizations/$organizationId/chat/$chatId/relay': typeof ApiOrganizationsOrganizationIdChatChatIdRelayRoute
  '/api/organizations/$organizationId/chat/$chatId/relay-approval': typeof ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute
  '/api/organizations/$organizationId/chat/$chatId/stop': typeof ApiOrganizationsOrganizationIdChatChatIdStopRoute
  '/api/organizations/$organizationId/chat/$chatId/stream': typeof ApiOrganizationsOrganizationIdChatChatIdStreamRoute
  '/api/organizations/$organizationId/content/$contentId/chat': typeof ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren
  '/api/organizations/$organizationId/dashboard-agent/chat/$chatId': typeof ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute
  '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId': typeof ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute
  '/api/organizations/$organizationId/content/$contentId/chat/$chatId': typeof ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/image': typeof ApiImageRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/external': typeof AuthExternalRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/brand-font/css': typeof ApiBrandFontCssRoute
  '/api/brand-font/file': typeof ApiBrandFontFileRoute
  '/api/command-palette/navigate': typeof ApiCommandPaletteNavigateRoute
  '/api/cron/brew-contacts': typeof ApiCronBrewContactsRoute
  '/api/cron/daily-summary': typeof ApiCronDailySummaryRoute
  '/api/cron/geo-content-gaps': typeof ApiCronGeoContentGapsRoute
  '/api/cron/geo-scan': typeof ApiCronGeoScanRoute
  '/api/cron/monitoring': typeof ApiCronMonitoringRoute
  '/api/cron/scheduled-publications': typeof ApiCronScheduledPublicationsRoute
  '/api/demo/enter': typeof ApiDemoEnterRoute
  '/api/demo/requests': typeof ApiDemoRequestsRouteWithChildren
  '/api/demo/sandbox': typeof ApiDemoSandboxRouteWithChildren
  '/api/geo/ingest': typeof ApiGeoIngestRoute
  '/api/social-accounts/callback': typeof ApiSocialAccountsCallbackRoute
  '/api/uploads/content-image': typeof ApiUploadsContentImageRoute
  '/api/uploads/convert-heic': typeof ApiUploadsConvertHeicRoute
  '/api/webhooks/workos': typeof ApiWebhooksWorkosRoute
  '/api/workflows/gsc-sync': typeof ApiWorkflowsGscSyncRoute
  '/api/workflows/iris': typeof ApiWorkflowsIrisRoute
  '/api/workflows/schedule': typeof ApiWorkflowsScheduleRoute
  '/api/workflows/scheduled-publication-wake': typeof ApiWorkflowsScheduledPublicationWakeRoute
  '/api/workflows/social-analytics-sync': typeof ApiWorkflowsSocialAnalyticsSyncRoute
  '/auth/social/callback': typeof AuthSocialCallbackRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/api/demo/requests/$requestId': typeof ApiDemoRequestsRequestIdRoute
  '/api/demo/sandbox/customize': typeof ApiDemoSandboxCustomizeRoute
  '/api/demo/sandbox/info': typeof ApiDemoSandboxInfoRoute
  '/api/demo/sandbox/reset': typeof ApiDemoSandboxResetRoute
  '/api/demo/sandbox/timezone': typeof ApiDemoSandboxTimezoneRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/google-search-console/authorize': typeof ApiIntegrationsGoogleSearchConsoleAuthorizeRoute
  '/api/integrations/google-search-console/callback': typeof ApiIntegrationsGoogleSearchConsoleCallbackRoute
  '/api/integrations/linear/authorize': typeof ApiIntegrationsLinearAuthorizeRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/internal/content/scheduled-publication-attempt': typeof ApiInternalContentScheduledPublicationAttemptRoute
  '/api/internal/content/sync-github': typeof ApiInternalContentSyncGithubRoute
  '/api/internal/geo/sequence-run': typeof ApiInternalGeoSequenceRunRoute
  '/api/internal/geo/writer-plan': typeof ApiInternalGeoWriterPlanRoute
  '/api/internal/workflows/agent-readiness': typeof ApiInternalWorkflowsAgentReadinessRoute
  '/api/internal/workflows/brand-analysis': typeof ApiInternalWorkflowsBrandAnalysisRoute
  '/api/internal/workflows/content-publication-sync-repair': typeof ApiInternalWorkflowsContentPublicationSyncRepairRoute
  '/api/internal/workflows/geo-scan': typeof ApiInternalWorkflowsGeoScanRoute
  '/api/internal/workflows/geo-writer': typeof ApiInternalWorkflowsGeoWriterRoute
  '/api/internal/workflows/on-demand-content': typeof ApiInternalWorkflowsOnDemandContentRoute
  '/api/organizations/$organizationId/chat': typeof ApiOrganizationsOrganizationIdChatRouteWithChildren
  '/api/uploads/content-images/$': typeof ApiUploadsContentImagesSplatRoute
  '/api/webhooks/github/app': typeof ApiWebhooksGithubAppRoute
  '/api/integrations/mcp/oauth/callback': typeof ApiIntegrationsMcpOauthCallbackRoute
  '/api/organizations/$organizationId/agent/$': typeof ApiOrganizationsOrganizationIdAgentSplatRoute
  '/api/organizations/$organizationId/dashboard-agent/chat': typeof ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren
  '/api/organizations/$organizationId/chat/$chatId/mirror-stream': typeof ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute
  '/api/organizations/$organizationId/chat/$chatId/relay': typeof ApiOrganizationsOrganizationIdChatChatIdRelayRoute
  '/api/organizations/$organizationId/chat/$chatId/relay-approval': typeof ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute
  '/api/organizations/$organizationId/chat/$chatId/stop': typeof ApiOrganizationsOrganizationIdChatChatIdStopRoute
  '/api/organizations/$organizationId/chat/$chatId/stream': typeof ApiOrganizationsOrganizationIdChatChatIdStreamRoute
  '/api/organizations/$organizationId/content/$contentId/chat': typeof ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren
  '/api/organizations/$organizationId/dashboard-agent/chat/$chatId': typeof ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute
  '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId': typeof ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute
  '/api/organizations/$organizationId/content/$contentId/chat/$chatId': typeof ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/.well-known/oauth-authorization-server'
    | '/api/healthcheck'
    | '/api/image'
    | '/api/realtime'
    | '/api/session'
    | '/auth/callback'
    | '/auth/external'
    | '/auth/initiate'
    | '/rpc/$'
    | '/rpc/'
    | '/api/autumn/$'
    | '/api/brand-font/css'
    | '/api/brand-font/file'
    | '/api/command-palette/navigate'
    | '/api/cron/brew-contacts'
    | '/api/cron/daily-summary'
    | '/api/cron/geo-content-gaps'
    | '/api/cron/geo-scan'
    | '/api/cron/monitoring'
    | '/api/cron/scheduled-publications'
    | '/api/demo/enter'
    | '/api/demo/requests'
    | '/api/demo/sandbox'
    | '/api/geo/ingest'
    | '/api/social-accounts/callback'
    | '/api/uploads/content-image'
    | '/api/uploads/convert-heic'
    | '/api/webhooks/workos'
    | '/api/workflows/gsc-sync'
    | '/api/workflows/iris'
    | '/api/workflows/schedule'
    | '/api/workflows/scheduled-publication-wake'
    | '/api/workflows/social-analytics-sync'
    | '/auth/social/callback'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/api/demo/requests/$requestId'
    | '/api/demo/sandbox/customize'
    | '/api/demo/sandbox/info'
    | '/api/demo/sandbox/reset'
    | '/api/demo/sandbox/timezone'
    | '/api/integrations/github/callback'
    | '/api/integrations/google-search-console/authorize'
    | '/api/integrations/google-search-console/callback'
    | '/api/integrations/linear/authorize'
    | '/api/integrations/linear/callback'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/api/internal/content/scheduled-publication-attempt'
    | '/api/internal/content/sync-github'
    | '/api/internal/geo/sequence-run'
    | '/api/internal/geo/writer-plan'
    | '/api/internal/workflows/agent-readiness'
    | '/api/internal/workflows/brand-analysis'
    | '/api/internal/workflows/content-publication-sync-repair'
    | '/api/internal/workflows/geo-scan'
    | '/api/internal/workflows/geo-writer'
    | '/api/internal/workflows/on-demand-content'
    | '/api/organizations/$organizationId/chat'
    | '/api/uploads/content-images/$'
    | '/api/webhooks/github/app'
    | '/api/integrations/mcp/oauth/callback'
    | '/api/organizations/$organizationId/agent/$'
    | '/api/organizations/$organizationId/dashboard-agent/chat'
    | '/api/organizations/$organizationId/chat/$chatId/mirror-stream'
    | '/api/organizations/$organizationId/chat/$chatId/relay'
    | '/api/organizations/$organizationId/chat/$chatId/relay-approval'
    | '/api/organizations/$organizationId/chat/$chatId/stop'
    | '/api/organizations/$organizationId/chat/$chatId/stream'
    | '/api/organizations/$organizationId/content/$contentId/chat'
    | '/api/organizations/$organizationId/dashboard-agent/chat/$chatId'
    | '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
    | '/api/organizations/$organizationId/content/$contentId/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/.well-known/oauth-authorization-server'
    | '/api/healthcheck'
    | '/api/image'
    | '/api/realtime'
    | '/api/session'
    | '/auth/callback'
    | '/auth/external'
    | '/auth/initiate'
    | '/rpc/$'
    | '/rpc'
    | '/api/autumn/$'
    | '/api/brand-font/css'
    | '/api/brand-font/file'
    | '/api/command-palette/navigate'
    | '/api/cron/brew-contacts'
    | '/api/cron/daily-summary'
    | '/api/cron/geo-content-gaps'
    | '/api/cron/geo-scan'
    | '/api/cron/monitoring'
    | '/api/cron/scheduled-publications'
    | '/api/demo/enter'
    | '/api/demo/requests'
    | '/api/demo/sandbox'
    | '/api/geo/ingest'
    | '/api/social-accounts/callback'
    | '/api/uploads/content-image'
    | '/api/uploads/convert-heic'
    | '/api/webhooks/workos'
    | '/api/workflows/gsc-sync'
    | '/api/workflows/iris'
    | '/api/workflows/schedule'
    | '/api/workflows/scheduled-publication-wake'
    | '/api/workflows/social-analytics-sync'
    | '/auth/social/callback'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/api/demo/requests/$requestId'
    | '/api/demo/sandbox/customize'
    | '/api/demo/sandbox/info'
    | '/api/demo/sandbox/reset'
    | '/api/demo/sandbox/timezone'
    | '/api/integrations/github/callback'
    | '/api/integrations/google-search-console/authorize'
    | '/api/integrations/google-search-console/callback'
    | '/api/integrations/linear/authorize'
    | '/api/integrations/linear/callback'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/api/internal/content/scheduled-publication-attempt'
    | '/api/internal/content/sync-github'
    | '/api/internal/geo/sequence-run'
    | '/api/internal/geo/writer-plan'
    | '/api/internal/workflows/agent-readiness'
    | '/api/internal/workflows/brand-analysis'
    | '/api/internal/workflows/content-publication-sync-repair'
    | '/api/internal/workflows/geo-scan'
    | '/api/internal/workflows/geo-writer'
    | '/api/internal/workflows/on-demand-content'
    | '/api/organizations/$organizationId/chat'
    | '/api/uploads/content-images/$'
    | '/api/webhooks/github/app'
    | '/api/integrations/mcp/oauth/callback'
    | '/api/organizations/$organizationId/agent/$'
    | '/api/organizations/$organizationId/dashboard-agent/chat'
    | '/api/organizations/$organizationId/chat/$chatId/mirror-stream'
    | '/api/organizations/$organizationId/chat/$chatId/relay'
    | '/api/organizations/$organizationId/chat/$chatId/relay-approval'
    | '/api/organizations/$organizationId/chat/$chatId/stop'
    | '/api/organizations/$organizationId/chat/$chatId/stream'
    | '/api/organizations/$organizationId/content/$contentId/chat'
    | '/api/organizations/$organizationId/dashboard-agent/chat/$chatId'
    | '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
    | '/api/organizations/$organizationId/content/$contentId/chat/$chatId'
  id:
    | '__root__'
    | '/.well-known/oauth-authorization-server'
    | '/api/healthcheck'
    | '/api/image'
    | '/api/realtime'
    | '/api/session'
    | '/auth/callback'
    | '/auth/external'
    | '/auth/initiate'
    | '/rpc/$'
    | '/rpc/'
    | '/api/autumn/$'
    | '/api/brand-font/css'
    | '/api/brand-font/file'
    | '/api/command-palette/navigate'
    | '/api/cron/brew-contacts'
    | '/api/cron/daily-summary'
    | '/api/cron/geo-content-gaps'
    | '/api/cron/geo-scan'
    | '/api/cron/monitoring'
    | '/api/cron/scheduled-publications'
    | '/api/demo/enter'
    | '/api/demo/requests'
    | '/api/demo/sandbox'
    | '/api/geo/ingest'
    | '/api/social-accounts/callback'
    | '/api/uploads/content-image'
    | '/api/uploads/convert-heic'
    | '/api/webhooks/workos'
    | '/api/workflows/gsc-sync'
    | '/api/workflows/iris'
    | '/api/workflows/schedule'
    | '/api/workflows/scheduled-publication-wake'
    | '/api/workflows/social-analytics-sync'
    | '/auth/social/callback'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/api/demo/requests/$requestId'
    | '/api/demo/sandbox/customize'
    | '/api/demo/sandbox/info'
    | '/api/demo/sandbox/reset'
    | '/api/demo/sandbox/timezone'
    | '/api/integrations/github/callback'
    | '/api/integrations/google-search-console/authorize'
    | '/api/integrations/google-search-console/callback'
    | '/api/integrations/linear/authorize'
    | '/api/integrations/linear/callback'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/api/internal/content/scheduled-publication-attempt'
    | '/api/internal/content/sync-github'
    | '/api/internal/geo/sequence-run'
    | '/api/internal/geo/writer-plan'
    | '/api/internal/workflows/agent-readiness'
    | '/api/internal/workflows/brand-analysis'
    | '/api/internal/workflows/content-publication-sync-repair'
    | '/api/internal/workflows/geo-scan'
    | '/api/internal/workflows/geo-writer'
    | '/api/internal/workflows/on-demand-content'
    | '/api/organizations/$organizationId/chat'
    | '/api/uploads/content-images/$'
    | '/api/webhooks/github/app'
    | '/api/integrations/mcp/oauth/callback'
    | '/api/organizations/$organizationId/agent/$'
    | '/api/organizations/$organizationId/dashboard-agent/chat'
    | '/api/organizations/$organizationId/chat/$chatId/mirror-stream'
    | '/api/organizations/$organizationId/chat/$chatId/relay'
    | '/api/organizations/$organizationId/chat/$chatId/relay-approval'
    | '/api/organizations/$organizationId/chat/$chatId/stop'
    | '/api/organizations/$organizationId/chat/$chatId/stream'
    | '/api/organizations/$organizationId/content/$contentId/chat'
    | '/api/organizations/$organizationId/dashboard-agent/chat/$chatId'
    | '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
    | '/api/organizations/$organizationId/content/$contentId/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiSessionRoute: typeof ApiSessionRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthExternalRoute: typeof AuthExternalRoute
  AuthInitiateRoute: typeof AuthInitiateRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcIndexRoute: typeof RpcIndexRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
  ApiBrandFontCssRoute: typeof ApiBrandFontCssRoute
  ApiBrandFontFileRoute: typeof ApiBrandFontFileRoute
  ApiCommandPaletteNavigateRoute: typeof ApiCommandPaletteNavigateRoute
  ApiCronBrewContactsRoute: typeof ApiCronBrewContactsRoute
  ApiCronDailySummaryRoute: typeof ApiCronDailySummaryRoute
  ApiCronGeoContentGapsRoute: typeof ApiCronGeoContentGapsRoute
  ApiCronGeoScanRoute: typeof ApiCronGeoScanRoute
  ApiCronMonitoringRoute: typeof ApiCronMonitoringRoute
  ApiCronScheduledPublicationsRoute: typeof ApiCronScheduledPublicationsRoute
  ApiDemoEnterRoute: typeof ApiDemoEnterRoute
  ApiDemoRequestsRoute: typeof ApiDemoRequestsRouteWithChildren
  ApiDemoSandboxRoute: typeof ApiDemoSandboxRouteWithChildren
  ApiGeoIngestRoute: typeof ApiGeoIngestRoute
  ApiSocialAccountsCallbackRoute: typeof ApiSocialAccountsCallbackRoute
  ApiUploadsContentImageRoute: typeof ApiUploadsContentImageRoute
  ApiUploadsConvertHeicRoute: typeof ApiUploadsConvertHeicRoute
  ApiWebhooksWorkosRoute: typeof ApiWebhooksWorkosRoute
  ApiWorkflowsGscSyncRoute: typeof ApiWorkflowsGscSyncRoute
  ApiWorkflowsIrisRoute: typeof ApiWorkflowsIrisRoute
  ApiWorkflowsScheduleRoute: typeof ApiWorkflowsScheduleRoute
  ApiWorkflowsScheduledPublicationWakeRoute: typeof ApiWorkflowsScheduledPublicationWakeRoute
  ApiWorkflowsSocialAnalyticsSyncRoute: typeof ApiWorkflowsSocialAnalyticsSyncRoute
  AuthSocialCallbackRoute: typeof AuthSocialCallbackRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsGoogleSearchConsoleAuthorizeRoute: typeof ApiIntegrationsGoogleSearchConsoleAuthorizeRoute
  ApiIntegrationsGoogleSearchConsoleCallbackRoute: typeof ApiIntegrationsGoogleSearchConsoleCallbackRoute
  ApiIntegrationsLinearAuthorizeRoute: typeof ApiIntegrationsLinearAuthorizeRoute
  ApiIntegrationsLinearCallbackRoute: typeof ApiIntegrationsLinearCallbackRoute
  ApiIntegrationsSlackAuthorizeRoute: typeof ApiIntegrationsSlackAuthorizeRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
  ApiInternalContentScheduledPublicationAttemptRoute: typeof ApiInternalContentScheduledPublicationAttemptRoute
  ApiInternalContentSyncGithubRoute: typeof ApiInternalContentSyncGithubRoute
  ApiInternalGeoSequenceRunRoute: typeof ApiInternalGeoSequenceRunRoute
  ApiInternalGeoWriterPlanRoute: typeof ApiInternalGeoWriterPlanRoute
  ApiInternalWorkflowsAgentReadinessRoute: typeof ApiInternalWorkflowsAgentReadinessRoute
  ApiInternalWorkflowsBrandAnalysisRoute: typeof ApiInternalWorkflowsBrandAnalysisRoute
  ApiInternalWorkflowsContentPublicationSyncRepairRoute: typeof ApiInternalWorkflowsContentPublicationSyncRepairRoute
  ApiInternalWorkflowsGeoScanRoute: typeof ApiInternalWorkflowsGeoScanRoute
  ApiInternalWorkflowsGeoWriterRoute: typeof ApiInternalWorkflowsGeoWriterRoute
  ApiInternalWorkflowsOnDemandContentRoute: typeof ApiInternalWorkflowsOnDemandContentRoute
  ApiOrganizationsOrganizationIdChatRoute: typeof ApiOrganizationsOrganizationIdChatRouteWithChildren
  ApiUploadsContentImagesSplatRoute: typeof ApiUploadsContentImagesSplatRoute
  ApiWebhooksGithubAppRoute: typeof ApiWebhooksGithubAppRoute
  ApiIntegrationsMcpOauthCallbackRoute: typeof ApiIntegrationsMcpOauthCallbackRoute
  ApiOrganizationsOrganizationIdAgentSplatRoute: typeof ApiOrganizationsOrganizationIdAgentSplatRoute
  ApiOrganizationsOrganizationIdDashboardAgentChatRoute: typeof ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren
  ApiOrganizationsOrganizationIdContentContentIdChatRoute: typeof ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren
  ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute: typeof ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/external': {
      id: '/auth/external'
      path: '/auth/external'
      fullPath: '/auth/external'
      preLoaderRoute: typeof AuthExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/initiate': {
      id: '/auth/initiate'
      path: '/auth/initiate'
      fullPath: '/auth/initiate'
      preLoaderRoute: typeof AuthInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/': {
      id: '/rpc/'
      path: '/rpc'
      fullPath: '/rpc/'
      preLoaderRoute: typeof RpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-font/css': {
      id: '/api/brand-font/css'
      path: '/api/brand-font/css'
      fullPath: '/api/brand-font/css'
      preLoaderRoute: typeof ApiBrandFontCssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-font/file': {
      id: '/api/brand-font/file'
      path: '/api/brand-font/file'
      fullPath: '/api/brand-font/file'
      preLoaderRoute: typeof ApiBrandFontFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/command-palette/navigate': {
      id: '/api/command-palette/navigate'
      path: '/api/command-palette/navigate'
      fullPath: '/api/command-palette/navigate'
      preLoaderRoute: typeof ApiCommandPaletteNavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/brew-contacts': {
      id: '/api/cron/brew-contacts'
      path: '/api/cron/brew-contacts'
      fullPath: '/api/cron/brew-contacts'
      preLoaderRoute: typeof ApiCronBrewContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-summary': {
      id: '/api/cron/daily-summary'
      path: '/api/cron/daily-summary'
      fullPath: '/api/cron/daily-summary'
      preLoaderRoute: typeof ApiCronDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/geo-content-gaps': {
      id: '/api/cron/geo-content-gaps'
      path: '/api/cron/geo-content-gaps'
      fullPath: '/api/cron/geo-content-gaps'
      preLoaderRoute: typeof ApiCronGeoContentGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/geo-scan': {
      id: '/api/cron/geo-scan'
      path: '/api/cron/geo-scan'
      fullPath: '/api/cron/geo-scan'
      preLoaderRoute: typeof ApiCronGeoScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/monitoring': {
      id: '/api/cron/monitoring'
      path: '/api/cron/monitoring'
      fullPath: '/api/cron/monitoring'
      preLoaderRoute: typeof ApiCronMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/scheduled-publications': {
      id: '/api/cron/scheduled-publications'
      path: '/api/cron/scheduled-publications'
      fullPath: '/api/cron/scheduled-publications'
      preLoaderRoute: typeof ApiCronScheduledPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/enter': {
      id: '/api/demo/enter'
      path: '/api/demo/enter'
      fullPath: '/api/demo/enter'
      preLoaderRoute: typeof ApiDemoEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/requests': {
      id: '/api/demo/requests'
      path: '/api/demo/requests'
      fullPath: '/api/demo/requests'
      preLoaderRoute: typeof ApiDemoRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/sandbox': {
      id: '/api/demo/sandbox'
      path: '/api/demo/sandbox'
      fullPath: '/api/demo/sandbox'
      preLoaderRoute: typeof ApiDemoSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/ingest': {
      id: '/api/geo/ingest'
      path: '/api/geo/ingest'
      fullPath: '/api/geo/ingest'
      preLoaderRoute: typeof ApiGeoIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-accounts/callback': {
      id: '/api/social-accounts/callback'
      path: '/api/social-accounts/callback'
      fullPath: '/api/social-accounts/callback'
      preLoaderRoute: typeof ApiSocialAccountsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/content-image': {
      id: '/api/uploads/content-image'
      path: '/api/uploads/content-image'
      fullPath: '/api/uploads/content-image'
      preLoaderRoute: typeof ApiUploadsContentImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/convert-heic': {
      id: '/api/uploads/convert-heic'
      path: '/api/uploads/convert-heic'
      fullPath: '/api/uploads/convert-heic'
      preLoaderRoute: typeof ApiUploadsConvertHeicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/workos': {
      id: '/api/webhooks/workos'
      path: '/api/webhooks/workos'
      fullPath: '/api/webhooks/workos'
      preLoaderRoute: typeof ApiWebhooksWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/gsc-sync': {
      id: '/api/workflows/gsc-sync'
      path: '/api/workflows/gsc-sync'
      fullPath: '/api/workflows/gsc-sync'
      preLoaderRoute: typeof ApiWorkflowsGscSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/iris': {
      id: '/api/workflows/iris'
      path: '/api/workflows/iris'
      fullPath: '/api/workflows/iris'
      preLoaderRoute: typeof ApiWorkflowsIrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/schedule': {
      id: '/api/workflows/schedule'
      path: '/api/workflows/schedule'
      fullPath: '/api/workflows/schedule'
      preLoaderRoute: typeof ApiWorkflowsScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/scheduled-publication-wake': {
      id: '/api/workflows/scheduled-publication-wake'
      path: '/api/workflows/scheduled-publication-wake'
      fullPath: '/api/workflows/scheduled-publication-wake'
      preLoaderRoute: typeof ApiWorkflowsScheduledPublicationWakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/social-analytics-sync': {
      id: '/api/workflows/social-analytics-sync'
      path: '/api/workflows/social-analytics-sync'
      fullPath: '/api/workflows/social-analytics-sync'
      preLoaderRoute: typeof ApiWorkflowsSocialAnalyticsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/social/callback': {
      id: '/auth/social/callback'
      path: '/auth/social/callback'
      fullPath: '/auth/social/callback'
      preLoaderRoute: typeof AuthSocialCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
    '/api/demo/requests/$requestId': {
      id: '/api/demo/requests/$requestId'
      path: '/$requestId'
      fullPath: '/api/demo/requests/$requestId'
      preLoaderRoute: typeof ApiDemoRequestsRequestIdRouteImport
      parentRoute: typeof ApiDemoRequestsRoute
    }
    '/api/demo/sandbox/customize': {
      id: '/api/demo/sandbox/customize'
      path: '/customize'
      fullPath: '/api/demo/sandbox/customize'
      preLoaderRoute: typeof ApiDemoSandboxCustomizeRouteImport
      parentRoute: typeof ApiDemoSandboxRoute
    }
    '/api/demo/sandbox/info': {
      id: '/api/demo/sandbox/info'
      path: '/info'
      fullPath: '/api/demo/sandbox/info'
      preLoaderRoute: typeof ApiDemoSandboxInfoRouteImport
      parentRoute: typeof ApiDemoSandboxRoute
    }
    '/api/demo/sandbox/reset': {
      id: '/api/demo/sandbox/reset'
      path: '/reset'
      fullPath: '/api/demo/sandbox/reset'
      preLoaderRoute: typeof ApiDemoSandboxResetRouteImport
      parentRoute: typeof ApiDemoSandboxRoute
    }
    '/api/demo/sandbox/timezone': {
      id: '/api/demo/sandbox/timezone'
      path: '/timezone'
      fullPath: '/api/demo/sandbox/timezone'
      preLoaderRoute: typeof ApiDemoSandboxTimezoneRouteImport
      parentRoute: typeof ApiDemoSandboxRoute
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-search-console/authorize': {
      id: '/api/integrations/google-search-console/authorize'
      path: '/api/integrations/google-search-console/authorize'
      fullPath: '/api/integrations/google-search-console/authorize'
      preLoaderRoute: typeof ApiIntegrationsGoogleSearchConsoleAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-search-console/callback': {
      id: '/api/integrations/google-search-console/callback'
      path: '/api/integrations/google-search-console/callback'
      fullPath: '/api/integrations/google-search-console/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleSearchConsoleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linear/authorize': {
      id: '/api/integrations/linear/authorize'
      path: '/api/integrations/linear/authorize'
      fullPath: '/api/integrations/linear/authorize'
      preLoaderRoute: typeof ApiIntegrationsLinearAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linear/callback': {
      id: '/api/integrations/linear/callback'
      path: '/api/integrations/linear/callback'
      fullPath: '/api/integrations/linear/callback'
      preLoaderRoute: typeof ApiIntegrationsLinearCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/authorize': {
      id: '/api/integrations/slack/authorize'
      path: '/api/integrations/slack/authorize'
      fullPath: '/api/integrations/slack/authorize'
      preLoaderRoute: typeof ApiIntegrationsSlackAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/content/scheduled-publication-attempt': {
      id: '/api/internal/content/scheduled-publication-attempt'
      path: '/api/internal/content/scheduled-publication-attempt'
      fullPath: '/api/internal/content/scheduled-publication-attempt'
      preLoaderRoute: typeof ApiInternalContentScheduledPublicationAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/content/sync-github': {
      id: '/api/internal/content/sync-github'
      path: '/api/internal/content/sync-github'
      fullPath: '/api/internal/content/sync-github'
      preLoaderRoute: typeof ApiInternalContentSyncGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/geo/sequence-run': {
      id: '/api/internal/geo/sequence-run'
      path: '/api/internal/geo/sequence-run'
      fullPath: '/api/internal/geo/sequence-run'
      preLoaderRoute: typeof ApiInternalGeoSequenceRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/geo/writer-plan': {
      id: '/api/internal/geo/writer-plan'
      path: '/api/internal/geo/writer-plan'
      fullPath: '/api/internal/geo/writer-plan'
      preLoaderRoute: typeof ApiInternalGeoWriterPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/agent-readiness': {
      id: '/api/internal/workflows/agent-readiness'
      path: '/api/internal/workflows/agent-readiness'
      fullPath: '/api/internal/workflows/agent-readiness'
      preLoaderRoute: typeof ApiInternalWorkflowsAgentReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/brand-analysis': {
      id: '/api/internal/workflows/brand-analysis'
      path: '/api/internal/workflows/brand-analysis'
      fullPath: '/api/internal/workflows/brand-analysis'
      preLoaderRoute: typeof ApiInternalWorkflowsBrandAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/content-publication-sync-repair': {
      id: '/api/internal/workflows/content-publication-sync-repair'
      path: '/api/internal/workflows/content-publication-sync-repair'
      fullPath: '/api/internal/workflows/content-publication-sync-repair'
      preLoaderRoute: typeof ApiInternalWorkflowsContentPublicationSyncRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/geo-scan': {
      id: '/api/internal/workflows/geo-scan'
      path: '/api/internal/workflows/geo-scan'
      fullPath: '/api/internal/workflows/geo-scan'
      preLoaderRoute: typeof ApiInternalWorkflowsGeoScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/geo-writer': {
      id: '/api/internal/workflows/geo-writer'
      path: '/api/internal/workflows/geo-writer'
      fullPath: '/api/internal/workflows/geo-writer'
      preLoaderRoute: typeof ApiInternalWorkflowsGeoWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/workflows/on-demand-content': {
      id: '/api/internal/workflows/on-demand-content'
      path: '/api/internal/workflows/on-demand-content'
      fullPath: '/api/internal/workflows/on-demand-content'
      preLoaderRoute: typeof ApiInternalWorkflowsOnDemandContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/chat': {
      id: '/api/organizations/$organizationId/chat'
      path: '/api/organizations/$organizationId/chat'
      fullPath: '/api/organizations/$organizationId/chat'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/content-images/$': {
      id: '/api/uploads/content-images/$'
      path: '/api/uploads/content-images/$'
      fullPath: '/api/uploads/content-images/$'
      preLoaderRoute: typeof ApiUploadsContentImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github/app': {
      id: '/api/webhooks/github/app'
      path: '/api/webhooks/github/app'
      fullPath: '/api/webhooks/github/app'
      preLoaderRoute: typeof ApiWebhooksGithubAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/mcp/oauth/callback': {
      id: '/api/integrations/mcp/oauth/callback'
      path: '/api/integrations/mcp/oauth/callback'
      fullPath: '/api/integrations/mcp/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsMcpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/agent/$': {
      id: '/api/organizations/$organizationId/agent/$'
      path: '/api/organizations/$organizationId/agent/$'
      fullPath: '/api/organizations/$organizationId/agent/$'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdAgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/dashboard-agent/chat': {
      id: '/api/organizations/$organizationId/dashboard-agent/chat'
      path: '/api/organizations/$organizationId/dashboard-agent/chat'
      fullPath: '/api/organizations/$organizationId/dashboard-agent/chat'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdDashboardAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/chat/$chatId/mirror-stream': {
      id: '/api/organizations/$organizationId/chat/$chatId/mirror-stream'
      path: '/$chatId/mirror-stream'
      fullPath: '/api/organizations/$organizationId/chat/$chatId/mirror-stream'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdChatRoute
    }
    '/api/organizations/$organizationId/chat/$chatId/relay': {
      id: '/api/organizations/$organizationId/chat/$chatId/relay'
      path: '/$chatId/relay'
      fullPath: '/api/organizations/$organizationId/chat/$chatId/relay'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatChatIdRelayRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdChatRoute
    }
    '/api/organizations/$organizationId/chat/$chatId/relay-approval': {
      id: '/api/organizations/$organizationId/chat/$chatId/relay-approval'
      path: '/$chatId/relay-approval'
      fullPath: '/api/organizations/$organizationId/chat/$chatId/relay-approval'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdChatRoute
    }
    '/api/organizations/$organizationId/chat/$chatId/stop': {
      id: '/api/organizations/$organizationId/chat/$chatId/stop'
      path: '/$chatId/stop'
      fullPath: '/api/organizations/$organizationId/chat/$chatId/stop'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatChatIdStopRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdChatRoute
    }
    '/api/organizations/$organizationId/chat/$chatId/stream': {
      id: '/api/organizations/$organizationId/chat/$chatId/stream'
      path: '/$chatId/stream'
      fullPath: '/api/organizations/$organizationId/chat/$chatId/stream'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdChatChatIdStreamRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdChatRoute
    }
    '/api/organizations/$organizationId/content/$contentId/chat': {
      id: '/api/organizations/$organizationId/content/$contentId/chat'
      path: '/api/organizations/$organizationId/content/$contentId/chat'
      fullPath: '/api/organizations/$organizationId/content/$contentId/chat'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdContentContentIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/dashboard-agent/chat/$chatId': {
      id: '/api/organizations/$organizationId/dashboard-agent/chat/$chatId'
      path: '/$chatId'
      fullPath: '/api/organizations/$organizationId/dashboard-agent/chat/$chatId'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdDashboardAgentChatRoute
    }
    '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId': {
      id: '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
      path: '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
      fullPath: '/api/webhooks/$provider/$organizationId/$integrationId/$repositoryId'
      preLoaderRoute: typeof ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/content/$contentId/chat/$chatId': {
      id: '/api/organizations/$organizationId/content/$contentId/chat/$chatId'
      path: '/$chatId'
      fullPath: '/api/organizations/$organizationId/content/$contentId/chat/$chatId'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdContentContentIdChatChatIdRouteImport
      parentRoute: typeof ApiOrganizationsOrganizationIdContentContentIdChatRoute
    }
  }
}

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerApiAuthRoute:
      DotwellKnownOauthAuthorizationServerApiAuthRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

interface ApiDemoRequestsRouteChildren {
  ApiDemoRequestsRequestIdRoute: typeof ApiDemoRequestsRequestIdRoute
}

const ApiDemoRequestsRouteChildren: ApiDemoRequestsRouteChildren = {
  ApiDemoRequestsRequestIdRoute: ApiDemoRequestsRequestIdRoute,
}

const ApiDemoRequestsRouteWithChildren = ApiDemoRequestsRoute._addFileChildren(
  ApiDemoRequestsRouteChildren,
)

interface ApiDemoSandboxRouteChildren {
  ApiDemoSandboxCustomizeRoute: typeof ApiDemoSandboxCustomizeRoute
  ApiDemoSandboxInfoRoute: typeof ApiDemoSandboxInfoRoute
  ApiDemoSandboxResetRoute: typeof ApiDemoSandboxResetRoute
  ApiDemoSandboxTimezoneRoute: typeof ApiDemoSandboxTimezoneRoute
}

const ApiDemoSandboxRouteChildren: ApiDemoSandboxRouteChildren = {
  ApiDemoSandboxCustomizeRoute: ApiDemoSandboxCustomizeRoute,
  ApiDemoSandboxInfoRoute: ApiDemoSandboxInfoRoute,
  ApiDemoSandboxResetRoute: ApiDemoSandboxResetRoute,
  ApiDemoSandboxTimezoneRoute: ApiDemoSandboxTimezoneRoute,
}

const ApiDemoSandboxRouteWithChildren = ApiDemoSandboxRoute._addFileChildren(
  ApiDemoSandboxRouteChildren,
)

interface ApiOrganizationsOrganizationIdChatRouteChildren {
  ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute: typeof ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute
  ApiOrganizationsOrganizationIdChatChatIdRelayRoute: typeof ApiOrganizationsOrganizationIdChatChatIdRelayRoute
  ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute: typeof ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute
  ApiOrganizationsOrganizationIdChatChatIdStopRoute: typeof ApiOrganizationsOrganizationIdChatChatIdStopRoute
  ApiOrganizationsOrganizationIdChatChatIdStreamRoute: typeof ApiOrganizationsOrganizationIdChatChatIdStreamRoute
}

const ApiOrganizationsOrganizationIdChatRouteChildren: ApiOrganizationsOrganizationIdChatRouteChildren =
  {
    ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute:
      ApiOrganizationsOrganizationIdChatChatIdMirrorStreamRoute,
    ApiOrganizationsOrganizationIdChatChatIdRelayRoute:
      ApiOrganizationsOrganizationIdChatChatIdRelayRoute,
    ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute:
      ApiOrganizationsOrganizationIdChatChatIdRelayApprovalRoute,
    ApiOrganizationsOrganizationIdChatChatIdStopRoute:
      ApiOrganizationsOrganizationIdChatChatIdStopRoute,
    ApiOrganizationsOrganizationIdChatChatIdStreamRoute:
      ApiOrganizationsOrganizationIdChatChatIdStreamRoute,
  }

const ApiOrganizationsOrganizationIdChatRouteWithChildren =
  ApiOrganizationsOrganizationIdChatRoute._addFileChildren(
    ApiOrganizationsOrganizationIdChatRouteChildren,
  )

interface ApiOrganizationsOrganizationIdDashboardAgentChatRouteChildren {
  ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute: typeof ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute
}

const ApiOrganizationsOrganizationIdDashboardAgentChatRouteChildren: ApiOrganizationsOrganizationIdDashboardAgentChatRouteChildren =
  {
    ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute:
      ApiOrganizationsOrganizationIdDashboardAgentChatChatIdRoute,
  }

const ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren =
  ApiOrganizationsOrganizationIdDashboardAgentChatRoute._addFileChildren(
    ApiOrganizationsOrganizationIdDashboardAgentChatRouteChildren,
  )

interface ApiOrganizationsOrganizationIdContentContentIdChatRouteChildren {
  ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute: typeof ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute
}

const ApiOrganizationsOrganizationIdContentContentIdChatRouteChildren: ApiOrganizationsOrganizationIdContentContentIdChatRouteChildren =
  {
    ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute:
      ApiOrganizationsOrganizationIdContentContentIdChatChatIdRoute,
  }

const ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren =
  ApiOrganizationsOrganizationIdContentContentIdChatRoute._addFileChildren(
    ApiOrganizationsOrganizationIdContentContentIdChatRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiImageRoute: ApiImageRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiSessionRoute: ApiSessionRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthExternalRoute: AuthExternalRoute,
  AuthInitiateRoute: AuthInitiateRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcIndexRoute: RpcIndexRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
  ApiBrandFontCssRoute: ApiBrandFontCssRoute,
  ApiBrandFontFileRoute: ApiBrandFontFileRoute,
  ApiCommandPaletteNavigateRoute: ApiCommandPaletteNavigateRoute,
  ApiCronBrewContactsRoute: ApiCronBrewContactsRoute,
  ApiCronDailySummaryRoute: ApiCronDailySummaryRoute,
  ApiCronGeoContentGapsRoute: ApiCronGeoContentGapsRoute,
  ApiCronGeoScanRoute: ApiCronGeoScanRoute,
  ApiCronMonitoringRoute: ApiCronMonitoringRoute,
  ApiCronScheduledPublicationsRoute: ApiCronScheduledPublicationsRoute,
  ApiDemoEnterRoute: ApiDemoEnterRoute,
  ApiDemoRequestsRoute: ApiDemoRequestsRouteWithChildren,
  ApiDemoSandboxRoute: ApiDemoSandboxRouteWithChildren,
  ApiGeoIngestRoute: ApiGeoIngestRoute,
  ApiSocialAccountsCallbackRoute: ApiSocialAccountsCallbackRoute,
  ApiUploadsContentImageRoute: ApiUploadsContentImageRoute,
  ApiUploadsConvertHeicRoute: ApiUploadsConvertHeicRoute,
  ApiWebhooksWorkosRoute: ApiWebhooksWorkosRoute,
  ApiWorkflowsGscSyncRoute: ApiWorkflowsGscSyncRoute,
  ApiWorkflowsIrisRoute: ApiWorkflowsIrisRoute,
  ApiWorkflowsScheduleRoute: ApiWorkflowsScheduleRoute,
  ApiWorkflowsScheduledPublicationWakeRoute:
    ApiWorkflowsScheduledPublicationWakeRoute,
  ApiWorkflowsSocialAnalyticsSyncRoute: ApiWorkflowsSocialAnalyticsSyncRoute,
  AuthSocialCallbackRoute: AuthSocialCallbackRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsGoogleSearchConsoleAuthorizeRoute:
    ApiIntegrationsGoogleSearchConsoleAuthorizeRoute,
  ApiIntegrationsGoogleSearchConsoleCallbackRoute:
    ApiIntegrationsGoogleSearchConsoleCallbackRoute,
  ApiIntegrationsLinearAuthorizeRoute: ApiIntegrationsLinearAuthorizeRoute,
  ApiIntegrationsLinearCallbackRoute: ApiIntegrationsLinearCallbackRoute,
  ApiIntegrationsSlackAuthorizeRoute: ApiIntegrationsSlackAuthorizeRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
  ApiInternalContentScheduledPublicationAttemptRoute:
    ApiInternalContentScheduledPublicationAttemptRoute,
  ApiInternalContentSyncGithubRoute: ApiInternalContentSyncGithubRoute,
  ApiInternalGeoSequenceRunRoute: ApiInternalGeoSequenceRunRoute,
  ApiInternalGeoWriterPlanRoute: ApiInternalGeoWriterPlanRoute,
  ApiInternalWorkflowsAgentReadinessRoute:
    ApiInternalWorkflowsAgentReadinessRoute,
  ApiInternalWorkflowsBrandAnalysisRoute:
    ApiInternalWorkflowsBrandAnalysisRoute,
  ApiInternalWorkflowsContentPublicationSyncRepairRoute:
    ApiInternalWorkflowsContentPublicationSyncRepairRoute,
  ApiInternalWorkflowsGeoScanRoute: ApiInternalWorkflowsGeoScanRoute,
  ApiInternalWorkflowsGeoWriterRoute: ApiInternalWorkflowsGeoWriterRoute,
  ApiInternalWorkflowsOnDemandContentRoute:
    ApiInternalWorkflowsOnDemandContentRoute,
  ApiOrganizationsOrganizationIdChatRoute:
    ApiOrganizationsOrganizationIdChatRouteWithChildren,
  ApiUploadsContentImagesSplatRoute: ApiUploadsContentImagesSplatRoute,
  ApiWebhooksGithubAppRoute: ApiWebhooksGithubAppRoute,
  ApiIntegrationsMcpOauthCallbackRoute: ApiIntegrationsMcpOauthCallbackRoute,
  ApiOrganizationsOrganizationIdAgentSplatRoute:
    ApiOrganizationsOrganizationIdAgentSplatRoute,
  ApiOrganizationsOrganizationIdDashboardAgentChatRoute:
    ApiOrganizationsOrganizationIdDashboardAgentChatRouteWithChildren,
  ApiOrganizationsOrganizationIdContentContentIdChatRoute:
    ApiOrganizationsOrganizationIdContentContentIdChatRouteWithChildren,
  ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute:
    ApiWebhooksProviderOrganizationIdIntegrationIdRepositoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
