import type { UiLabels } from "@notra/ui/types/ui-labels";

export const DEFAULT_UI_LABELS: UiLabels = {
  close: "Close",
  cancel: "Cancel",
  copy: "Copy",
  copied: "Copied",
  more: "More",
  completed: "Completed",
  incomplete: "Incomplete",
  remove: "Remove",
  previous: "Previous",
  next: "Next",
  pagination: "pagination",
  goToPreviousPage: "Go to previous page",
  goToNextPage: "Go to next page",
  morePages: "More pages",
  paginationRange: (start, end, total) => `${start}-${end} of ${total}`,
  paginationRangeOpen: (start, end) => `${start}-${end}`,
  pageOf: (page, total) => `Page ${page} of ${total}`,
  pageNumber: (page) => `Page ${page}`,
  showRows: (count) => `Show ${count}`,
  rowsPerPage: "Rows per page",
  toggleSidebar: "Toggle Sidebar",
  sidebarTitle: "Sidebar",
  sidebarDescription: "Displays the mobile sidebar.",
  previousSlide: "Previous slide",
  nextSlide: "Next slide",
  scrollToEnd: "Scroll to end",
  scrollToStart: "Scroll to start",
  conversationTurns: "Conversation turns",
  previousTurn: "Previous turn",
  nextTurn: "Next turn",
  commandPaletteTitle: "Command Palette",
  commandPaletteDescription: "Search for a command to run...",
  chooseOption: "Choose an option",
  permissions: "Permissions",
  catalog: "Catalog",
  showPassword: "Show password",
  hidePassword: "Hide password",
  previousBranch: "Previous branch",
  nextBranch: "Next branch",
  table: "Table",
  noData: "No data",
  selectAllRows: "Select all rows",
  selectRow: (row) => `Select row ${row}`,
  resizeColumn: (column) => `Resize ${column} column`,
  copyTableAsMarkdown: "Copy table as Markdown",
  downloadTable: "Download table",
  viewTableFullscreen: "View table fullscreen",
  tableFormatCsv: "CSV",
  tableFormatMarkdown: "Markdown",
  tableFormatPlain: "Plain",
  image: "Image",
  attachment: "Attachment",
  removeAttachment: "Remove attachment",
  expandImage: "Expand image",
  minimizeImage: "Minimize image",
};
