export const NLWEB_VERSION = "0.55";
export const NLWEB_RESPONSE_FORMAT = "conversational_search";
export const NLWEB_MAX_RESULTS = 5;
export const NLWEB_MIN_SCORE = 1;

export const NLWEB_STOP_WORDS = new Set([
  "about",
  "and",
  "are",
  "can",
  "does",
  "for",
  "from",
  "hat",
  "how",
  "ich",
  "ist",
  "kann",
  "notra",
  "oder",
  "the",
  "this",
  "und",
  "viel",
  "was",
  "what",
  "where",
  "wie",
  "with",
  "you",
]);

export const NLWEB_QUERY_ALIASES: Record<string, string[]> = {
  authentication: ["auth", "oauth", "credential", "token"],
  authenticate: ["auth", "oauth", "credential", "token"],
  changelog: ["changelogs", "studio"],
  changelogs: ["changelog", "studio"],
  connect: ["connection", "endpoint", "integration", "server"],
  cost: ["price", "pricing", "plan"],
  costs: ["price", "pricing", "plan"],
  kostet: ["cost", "price", "pricing", "plan"],
  kosten: ["cost", "price", "pricing", "plan"],
  login: ["auth", "oauth", "credential"],
  monitor: ["track", "tracking"],
  plan: ["price", "pricing"],
  plans: ["price", "pricing"],
  preis: ["cost", "price", "pricing", "plan"],
  track: ["monitor", "tracking"],
  verbinden: ["connect", "connection", "integration"],
  verbindung: ["connect", "connection", "integration"],
  visit: ["traffic", "journey", "referral"],
  visited: ["traffic", "journey", "referral"],
  visits: ["traffic", "journey", "referral"],
  website: ["site"],
  write: ["draft", "drafts", "content"],
};
