export const CHAT_TOOL_LABEL_ALIASES = {
  getAvailableBrandReferences: "getBrandReferences",
  search: "webSearch",
  recall: "searchMemories",
  "code-researcher": "codeResearcher",
  "content-writer": "contentWriter",
  open_repository: "openRepository",
  list_repository_files: "listRepositoryFiles",
  search_repository: "searchRepository",
  read_repository_file: "readRepositoryFile",
  repository_history: "repositoryHistory",
  show_repository_change: "showRepositoryChange",
  create_post: "createPost",
  get_pull_requests: "getPullRequests",
  get_commits_by_timeframe: "getCommitsByTimeframe",
  get_available_integrations: "getAvailableIntegrations",
  list_available_skills: "listAvailableSkills",
  get_skill_by_name: "getSkillByName",
  get_brand_references: "getBrandReferences",
} as const;
