export const BREADCRUMB_SEGMENTS = [
  "accounts",
  "analytics",
  "api-keys",
  "automation",
  "billing",
  "brand",
  "chat",
  "collection",
  "content",
  "events",
  "feedback",
  "identity",
  "integrations",
  "iris",
  "leaderboard",
  "schedules",
  "settings",
  "sites",
  "skills",
  "usage",
] as const;

export const GEO_BREADCRUMB_SEGMENTS = [
  "agent-readiness",
  "competitors",
  "directions",
  "gaps",
  "personas",
  "prompts",
  "settings",
  "shelf-space",
  "traffic",
  "write",
] as const;
