export const DATABUDDY_DASHBOARD_WEBSITE_ID =
  process.env.NEXT_PUBLIC_DATABUDDY_DASHBOARD_WEBSITE_ID;

export const DATABUDDY_DEMO_DASHBOARD_WEBSITE_ID =
  process.env.NEXT_PUBLIC_DATABUDDY_DEMO_DASHBOARD_WEBSITE_ID;
