export const MODELS_DEV_LOGO_BASE = "https://models.dev/logos";

export const MODELS_DEV_LOGO_ALIASES: Record<string, string> = {
  amazon: "amazon-bedrock",
  "google-ai-studio": "google",
  "google-vertex": "google",
  "google-vertex-anthropic": "anthropic",
  "meta-llama": "meta",
  mistralai: "mistral",
  moonshot: "moonshotai",
  qwen: "alibaba",
  "x-ai": "xai",
  "z-ai": "zai",
  zhipuai: "zai",
};

export const MODEL_HYPHEN_PREFIXES = new Set(["glm", "gpt", "hy3", "mimo"]);

export const MODEL_TOKEN_LABELS: Record<string, string> = {
  claude: "Claude",
  coder: "Coder",
  composer: "Composer",
  deepseek: "DeepSeek",
  flash: "Flash",
  gemini: "Gemini",
  glm: "GLM",
  gpt: "GPT",
  grok: "Grok",
  haiku: "Haiku",
  hy3: "Hy3",
  instant: "Instant",
  instruct: "Instruct",
  kimi: "Kimi",
  llama: "Llama",
  lite: "Lite",
  luna: "Luna",
  magistral: "Magistral",
  max: "Max",
  mimo: "MiMo",
  mini: "mini",
  mistral: "Mistral",
  mixtral: "Mixtral",
  nano: "Nano",
  nemotron: "Nemotron",
  omni: "Omni",
  opus: "Opus",
  plus: "Plus",
  preview: "Preview",
  pro: "Pro",
  qwen: "Qwen",
  sol: "Sol",
  sonar: "Sonar",
  sonnet: "Sonnet",
  terra: "Terra",
  turbo: "Turbo",
  ultra: "Ultra",
};
