export const GEO_REPLAY_USER_PAUSE_MS = 420;
export const GEO_REPLAY_TURN_PAUSE_MS = 480;
export const GEO_REPLAY_REDUCED_MOTION_PAUSE_MS = 80;
export const GEO_REPLAY_TYPE_INTERVAL_MS = 24;
export const GEO_REPLAY_MIN_TYPE_INTERVAL_MS = 6;
export const GEO_REPLAY_MAX_TYPE_TOTAL_MS = 9000;
