import {
  AiBrowserIcon,
  AnalyticsUpIcon,
  Attachment01Icon,
  ChartAnalysisIcon,
  CorporateIcon,
  CreditCardIcon,
  Globe02Icon,
  Notification01Icon,
  PlugIcon,
  Settings01Icon,
  UserCircleIcon,
  UserGroupIcon,
  Wallet01Icon,
} from "@hugeicons/core-free-icons";

import type {
  SettingsNavGroup,
  SettingsSectionId,
} from "@/types/settings/modal";

export const SETTINGS_SECTION_IDS = [
  "account",
  "general",
  "members",
  "notifications",
  "attachments",
  "integrations",
  "billing",
  "usage",
  "credits",
  "logs",
  "geo",
  "geo-brand",
  "geo-languages",
  "geo-models",
] as const satisfies readonly SettingsSectionId[];

export const SETTINGS_QUERY_KEY = "settings";

export const SETTINGS_NAV_GROUPS: readonly SettingsNavGroup[] = [
  {
    id: "account",
    label: "Account",
    items: [
      {
        id: "account",
        label: "Account",
        description: "Profile, login, and privacy",
        icon: UserCircleIcon,
        keywords: [
          "profile",
          "user",
          "email",
          "password",
          "privacy",
          "chat",
          "avatar",
          "login",
          "google",
          "github",
          "name",
          "delete account",
        ],
      },
    ],
  },
  {
    id: "organization",
    label: "Organization",
    items: [
      {
        id: "general",
        label: "General",
        description: "Name, logo, and connected accounts",
        icon: Settings01Icon,
        keywords: [
          "organization",
          "workspace",
          "name",
          "logo",
          "slug",
          "twitter",
          "linkedin",
          "social",
          "domain",
        ],
      },
      {
        id: "members",
        label: "Members",
        description: "Team access and invitations",
        icon: UserGroupIcon,
        keywords: [
          "team",
          "users",
          "invite",
          "people",
          "roles",
          "owner",
          "admin",
          "pending",
        ],
      },
      {
        id: "notifications",
        label: "Notifications",
        description: "Email alerts and recaps",
        icon: Notification01Icon,
        keywords: [
          "alerts",
          "email",
          "preferences",
          "digest",
          "recap",
          "marketing",
          "product updates",
        ],
      },
      {
        id: "attachments",
        label: "Attachments",
        description: "Uploaded files",
        icon: Attachment01Icon,
        keywords: ["files", "uploads", "media", "pdf", "images", "storage"],
      },
      {
        id: "integrations",
        label: "Integrations",
        description: "GitHub, Linear, and other connections",
        icon: PlugIcon,
        keywords: [
          "github",
          "linear",
          "slack",
          "granola",
          "framer",
          "raycast",
          "repositories",
          "pull request",
          "draft",
          "connect",
        ],
      },
      {
        id: "billing",
        label: "Billing",
        description: "Plans, invoices, and subscription",
        icon: CreditCardIcon,
        keywords: [
          "subscription",
          "plan",
          "invoice",
          "payment",
          "stripe",
          "trial",
          "upgrade",
        ],
      },
      {
        id: "usage",
        label: "Usage",
        description: "Remaining quotas and usage",
        icon: ChartAnalysisIcon,
        keywords: [
          "usage",
          "remaining",
          "limits",
          "quota",
          "answers",
          "cycle",
          "breakdown",
        ],
      },
      {
        id: "credits",
        label: "Credits",
        description: "AI credit balance and top-ups",
        icon: Wallet01Icon,
        keywords: ["balance", "top up", "topup", "tokens", "ai", "spend"],
        requiresAiCredits: true,
      },
      {
        id: "logs",
        label: "Logs",
        description: "Integration events",
        icon: AnalyticsUpIcon,
        keywords: [
          "audit",
          "activity",
          "events",
          "webhooks",
          "history",
          "retention",
          "delivery",
        ],
      },
    ],
  },
  {
    id: "geo",
    label: "GEO",
    items: [
      {
        id: "geo-brand",
        label: "Brand",
        description: "Name, aliases, and conversion paths",
        icon: CorporateIcon,
        keywords: [
          "geo",
          "brand",
          "company",
          "aliases",
          "conversion",
          "paths",
          "tracking",
          "project",
          "identity",
        ],
      },
      {
        id: "geo-languages",
        label: "Languages",
        description: "Languages prompts are scanned in",
        icon: Globe02Icon,
        keywords: [
          "geo",
          "language",
          "locale",
          "translation",
          "english",
          "scan",
        ],
      },
      {
        id: "geo-models",
        label: "Models",
        description: "Engines, schedule, and scanning",
        icon: AiBrowserIcon,
        keywords: [
          "geo",
          "models",
          "engines",
          "scanning",
          "schedule",
          "zdr",
          "providers",
          "frequency",
          "openai",
          "anthropic",
          "muse",
        ],
      },
    ],
  },
];

export const SETTINGS_SECTION_LABELS: Record<SettingsSectionId, string> = {
  account: "Account",
  general: "General",
  members: "Members",
  notifications: "Notifications",
  attachments: "Attachments",
  integrations: "Integrations",
  billing: "Billing",
  usage: "Usage",
  credits: "Credits",
  logs: "Logs",
  geo: "Brand",
  "geo-brand": "Brand",
  "geo-languages": "Languages",
  "geo-models": "Models",
};

export const SETTINGS_SECTION_DESCRIPTIONS: Record<SettingsSectionId, string> =
  {
    account: "Manage your profile and account settings",
    general: "Manage your organization settings",
    members: "Manage who has access to this organization",
    notifications: "Configure email notifications for your organization",
    attachments: "Manage your uploaded files and attachments",
    integrations: "Open GitHub, Linear, and other connected services",
    billing: "Manage your plan, invoices, and subscription",
    usage: "See remaining quotas and usage over time",
    credits: "Monitor your AI credit balance and usage",
    logs: "View integration events and their delivery status",
    geo: "How your brand is identified in answers",
    "geo-brand": "How your brand is identified in answers",
    "geo-languages": "Languages your prompts are scanned in",
    "geo-models": "Which providers run, and how often",
  };

export const DEFAULT_SETTINGS_SECTION: SettingsSectionId = "account";
export const DEFAULT_GEO_SETTINGS_SECTION: SettingsSectionId = "geo-brand";

export const LOGS_SETTINGS_SEARCH_KEYS = [
  "q",
  "source",
  "status",
  "page",
] as const;

export const LEGACY_BILLING_TAB_VALUES = ["billing", "usage"] as const;
